package com.amani.model;



/**
 * S3area generated by MyEclipse - Hibernate Tools
 */

public class A3area  implements java.io.Serializable {


    // Fields    

     private A3areaId id;


    // Constructors

    /** default constructor */
    public A3area() {
    }

    
    /** full constructor */
    public A3area(A3areaId id) {
        this.id = id;
    }


	public A3areaId getId() {
		return id;
	}


	public void setId(A3areaId id) {
		this.id = id;
	}

   
   








}