package com.amani.model;



/**
 * S3areaId generated by MyEclipse - Hibernate Tools
 */

public class A3areaId  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String code;
     private String name;
     private String cityId;


    // Constructors

    /** default constructor */
    public A3areaId() {
    }

	/** minimal constructor */
    public A3areaId(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public A3areaId(Integer id, String code, String name, String cityId) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.cityId = cityId;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getCityId() {
        return this.cityId;
    }
    
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof A3areaId) ) return false;
		 A3areaId castOther = ( A3areaId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getCode()==castOther.getCode()) || ( this.getCode()!=null && castOther.getCode()!=null && this.getCode().equals(castOther.getCode()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getCityId()==castOther.getCityId()) || ( this.getCityId()!=null && castOther.getCityId()!=null && this.getCityId().equals(castOther.getCityId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getCode() == null ? 0 : this.getCode().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getCityId() == null ? 0 : this.getCityId().hashCode() );
         return result;
   }   





}