package com.amani.model;



/**
 * S3cityId generated by MyEclipse - Hibernate Tools
 */

public class A3cityId  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String code;
     private String name;
     private String provinceId;


    // Constructors

    /** default constructor */
    public A3cityId() {
    }

	/** minimal constructor */
    public A3cityId(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public A3cityId(Integer id, String code, String name, String provinceId) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.provinceId = provinceId;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getProvinceId() {
        return this.provinceId;
    }
    
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof A3cityId) ) return false;
		 A3cityId castOther = ( A3cityId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getCode()==castOther.getCode()) || ( this.getCode()!=null && castOther.getCode()!=null && this.getCode().equals(castOther.getCode()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getProvinceId()==castOther.getProvinceId()) || ( this.getProvinceId()!=null && castOther.getProvinceId()!=null && this.getProvinceId().equals(castOther.getProvinceId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getCode() == null ? 0 : this.getCode().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getProvinceId() == null ? 0 : this.getProvinceId().hashCode() );
         return result;
   }   





}