package com.amani.model;



/**
 * S3city generated by MyEclipse - Hibernate Tools
 */

public class A3city  implements java.io.Serializable {


    // Fields    

     private A3cityId id;


    // Constructors

    /** default constructor */
    public A3city() {
    }

    
    /** full constructor */
    public A3city(A3cityId id) {
        this.id = id;
    }

   
    // Property accessors

    public A3cityId getId() {
        return this.id;
    }
    
    public void setId(A3cityId id) {
        this.id = id;
    }
   








}