package com.amani.model;



/**
 * S3province generated by MyEclipse - Hibernate Tools
 */

public class A3province  implements java.io.Serializable {


    // Fields    

     private A3provinceId id;


    // Constructors

    /** default constructor */
    public A3province() {
    }

    
    /** full constructor */
    public A3province(A3provinceId id) {
        this.id = id;
    }

   
    // Property accessors

    public A3provinceId getId() {
        return this.id;
    }
    
    public void setId(A3provinceId id) {
        this.id = id;
    }
   








}