package com.amani.model;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class CardtypeinfoId  implements java.io.Serializable {


    // Fields    

     private String cardtypemodeid;
     private String cardtypeno;
     private String cardtypesource;	

     
     public CardtypeinfoId(String cardtypemodeid, String cardtypeno,String cardtypesource ) {
         this.cardtypemodeid = cardtypemodeid;
         this.cardtypeno = cardtypeno;
         this.cardtypesource=cardtypesource;
     }
     public CardtypeinfoId() {
     }
	public String getCardtypemodeid() {
		return cardtypemodeid;
	}
	public void setCardtypemodeid(String cardtypemodeid) {
		this.cardtypemodeid = cardtypemodeid;
	}
	public String getCardtypeno() {
		return cardtypeno;
	}
	public void setCardtypeno(String cardtypeno) {
		this.cardtypeno = cardtypeno;
	}
	public String getCardtypesource() {
		return cardtypesource;
	}
	public void setCardtypesource(String cardtypesource) {
		this.cardtypesource = cardtypesource;
	}
	
	
}