package com.amani.model;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class CardcostgoodsrateId  implements java.io.Serializable {


    // Fields    

     private String compid;
     private String goodstypeid;
     private String cardtypeno;
     private String acounttypeno;
     public CardcostgoodsrateId(String compid, String goodstypeid ,String cardtypeno ,String acounttypeno) {
         this.compid = compid;
         this.goodstypeid = goodstypeid;
         this.cardtypeno = cardtypeno;
         this.acounttypeno = acounttypeno;
     }
     public CardcostgoodsrateId() {
     }
	public String getCompid() {
		return compid;
	}
	public void setCompid(String compid) {
		this.compid = compid;
	}
	
	public String getGoodstypeid() {
		return goodstypeid;
	}
	public void setGoodstypeid(String goodstypeid) {
		this.goodstypeid = goodstypeid;
	}
	public String getCardtypeno() {
		return cardtypeno;
	}
	public void setCardtypeno(String cardtypeno) {
		this.cardtypeno = cardtypeno;
	}
	public String getAcounttypeno() {
		return acounttypeno;
	}
	public void setAcounttypeno(String acounttypeno) {
		this.acounttypeno = acounttypeno;
	}
	

}