package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class CardinfoId  implements java.io.Serializable {


    // Fields    

     private String cardvesting;
     private String cardno;

     
     public String getCardvesting() {
		return cardvesting;
	}
	public void setCardvesting(String cardvesting) {
		this.cardvesting = cardvesting;
	}
	public String getCardno() {
		return cardno;
	}
	public void setCardno(String cardno) {
		this.cardno = cardno;
	}
	public CardinfoId(String cardvesting, String cardno ) {
         this.cardvesting = cardvesting;
         this.cardno = cardno;
     }
     public CardinfoId() {
     }
	
	
}