package com.amani.model;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class CommoninfoId  implements java.io.Serializable {


    // Fields    

     private String infotype;
     private String codekey;
     private String parentcodekey;
     
     public CommoninfoId(String infotype, String parentcodekey ,String codekey ) {
         this.infotype = infotype;
         this.codekey = codekey;
         this.parentcodekey = parentcodekey;
     }
     public CommoninfoId() {
     }
	public String getParentcodekey() {
		return parentcodekey;
	}
	public void setParentcodekey(String parentcodekey) {
		this.parentcodekey = parentcodekey;
	}
	public String getInfotype() {
		return infotype;
	}
	public void setInfotype(String infotype) {
		this.infotype = infotype;
	}
	public String getCodekey() {
		return codekey;
	}
	public void setCodekey(String codekey) {
		this.codekey = codekey;
	}



}