package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DcardapponlineId  implements java.io.Serializable {


    // Fields    

     private String cappcompid;
     private String cappcompbillid;
     private Double cappseqno;
     
     public DcardapponlineId(String cappcompid, String cappcompbillid,double cappseqno ) {
         this.cappcompid = cappcompid;
         this.cappcompbillid = cappcompbillid;
         this.cappseqno=cappseqno;
     }
     public DcardapponlineId() {
     }
	public String getCappcompid() {
		return cappcompid;
	}
	public void setCappcompid(String cappcompid) {
		this.cappcompid = cappcompid;
	}
	public String getCappcompbillid() {
		return cappcompbillid;
	}
	public void setCappcompbillid(String cappcompbillid) {
		this.cappcompbillid = cappcompbillid;
	}
	public Double getCappseqno() {
		return cappseqno;
	}
	public void setCappseqno(Double cappseqno) {
		this.cappseqno = cappseqno;
	}
	
	
}