package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DcardallotmentId  implements java.io.Serializable {


    // Fields    

     private String callotcompid;
     private String callotbillid;
     private Double callotseqno;
     
     public DcardallotmentId(String callotcompid, String callotbillid,double callotseqno ) {
         this.callotcompid = callotcompid;
         this.callotbillid = callotbillid;
         this.callotseqno=callotseqno;
     }
     public DcardallotmentId() {
     }
	public String getCallotcompid() {
		return callotcompid;
	}
	public void setCallotcompid(String callotcompid) {
		this.callotcompid = callotcompid;
	}
	
	public String getCallotbillid() {
		return callotbillid;
	}
	public void setCallotbillid(String callotbillid) {
		this.callotbillid = callotbillid;
	}
	public Double getCallotseqno() {
		return callotseqno;
	}
	public void setCallotseqno(Double callotseqno) {
		this.callotseqno = callotseqno;
	}
	
	
}