package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DconsumeinfoId  implements java.io.Serializable {


    // Fields    

     private String cscompid;
     private String csbillid;
     private Integer csinfotype;
     private Double csseqno;
     
     public DconsumeinfoId(String cscompid, String csbillid,int csinfotype,double csseqno ) {
         this.cscompid = cscompid;
         this.csbillid = csbillid;
         this.csinfotype= csinfotype;
         this.csseqno=csseqno;
     }
     public DconsumeinfoId() {
     }
	public String getCscompid() {
		return cscompid;
	}
	public void setCscompid(String cscompid) {
		this.cscompid = cscompid;
	}
	public String getCsbillid() {
		return csbillid;
	}
	public void setCsbillid(String csbillid) {
		this.csbillid = csbillid;
	}
	public Integer getCsinfotype() {
		return csinfotype;
	}
	public void setCsinfotype(Integer csinfotype) {
		this.csinfotype = csinfotype;
	}
	public Double getCsseqno() {
		return csseqno;
	}
	public void setCsseqno(Double csseqno) {
		this.csseqno = csseqno;
	}
	
}