package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DgoodsinsertId  implements java.io.Serializable {


    // Fields    

     private String insercompid;
     private String inserbillid;
     private Double inserseqno;
     
     public DgoodsinsertId(String insercompid, String inserbillid,double inserseqno ) {
         this.insercompid = insercompid;
         this.inserbillid = inserbillid;
         this.inserseqno=inserseqno;
     }
     public DgoodsinsertId() {
     }
	public String getInsercompid() {
		return insercompid;
	}
	public void setInsercompid(String insercompid) {
		this.insercompid = insercompid;
	}
	public String getInserbillid() {
		return inserbillid;
	}
	public void setInserbillid(String inserbillid) {
		this.inserbillid = inserbillid;
	}
	public Double getInserseqno() {
		return inserseqno;
	}
	public void setInserseqno(Double inserseqno) {
		this.inserseqno = inserseqno;
	}
	
	
}