package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DgoodssendinfoId  implements java.io.Serializable {


    // Fields    

     private String sendcompid;
     private String sendbillid;
     private Double sendseqno;
     
     public DgoodssendinfoId(String sendcompid, String sendbillid,double sendseqno ) {
         this.sendcompid = sendcompid;
         this.sendbillid = sendbillid;
         this.sendseqno=sendseqno;
     }
     public DgoodssendinfoId() {
     }
	public String getSendcompid() {
		return sendcompid;
	}
	public void setSendcompid(String sendcompid) {
		this.sendcompid = sendcompid;
	}
	public String getSendbillid() {
		return sendbillid;
	}
	public void setSendbillid(String sendbillid) {
		this.sendbillid = sendbillid;
	}
	public Double getSendseqno() {
		return sendseqno;
	}
	public void setSendseqno(Double sendseqno) {
		this.sendseqno = sendseqno;
	}
	
}