package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DgoodsouterId  implements java.io.Serializable {


    // Fields    

     private String outercompid;
     private String outerbillid;
     private Double outerseqno;
     
     public DgoodsouterId(String outercompid, String outerbillid,double outerseqno ) {
         this.outercompid = outercompid;
         this.outerbillid = outerbillid;
         this.outerseqno=outerseqno;
     }
     public DgoodsouterId() {
     }
	public String getOutercompid() {
		return outercompid;
	}
	public void setOutercompid(String outercompid) {
		this.outercompid = outercompid;
	}
	public String getOuterbillid() {
		return outerbillid;
	}
	public void setOuterbillid(String outerbillid) {
		this.outerbillid = outerbillid;
	}
	public Double getOuterseqno() {
		return outerseqno;
	}
	public void setOuterseqno(Double outerseqno) {
		this.outerseqno = outerseqno;
	}
	
}