package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DgoodsreceiptId  implements java.io.Serializable {


    // Fields    

     private String receiptcompid;
     private String receiptbillid;
     private Double receiptseqno;
     
     public DgoodsreceiptId(String receiptcompid, String receiptbillid,double receiptseqno ) {
         this.receiptcompid = receiptcompid;
         this.receiptbillid = receiptbillid;
         this.receiptseqno=receiptseqno;
     }
     public DgoodsreceiptId() {
     }
	public String getReceiptcompid() {
		return receiptcompid;
	}
	public void setReceiptcompid(String receiptcompid) {
		this.receiptcompid = receiptcompid;
	}
	public String getReceiptbillid() {
		return receiptbillid;
	}
	public void setReceiptbillid(String receiptbillid) {
		this.receiptbillid = receiptbillid;
	}
	public Double getReceiptseqno() {
		return receiptseqno;
	}
	public void setReceiptseqno(Double receiptseqno) {
		this.receiptseqno = receiptseqno;
	}
	
}