package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DgoodsorderinfoId  implements java.io.Serializable {


    // Fields    

	 private String ordercompid;
     private String orderbillid;
     private Double orderseqno;
     
     public DgoodsorderinfoId()
     {
    	 
     }
     public DgoodsorderinfoId(String ordercompid, String orderbillid,double orderseqno ) {
         this.ordercompid = ordercompid;
         this.orderbillid = orderbillid;
         this.orderseqno=orderseqno;
     }

	public String getOrdercompid() {
		return ordercompid;
	}

	public void setOrdercompid(String ordercompid) {
		this.ordercompid = ordercompid;
	}

	public String getOrderbillid() {
		return orderbillid;
	}

	public void setOrderbillid(String orderbillid) {
		this.orderbillid = orderbillid;
	}

	public Double getOrderseqno() {
		return orderseqno;
	}

	public void setOrderseqno(Double orderseqno) {
		this.orderseqno = orderseqno;
	}
	
}