package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DgoodsstockinfoId  implements java.io.Serializable {


    // Fields    

     private String changecompid;
     private String changebillno;
     private String changetype;
     private Double changeseqno;
     
     public DgoodsstockinfoId(String changecompid, String changebillno,String changetype,double changeseqno ) {
         this.changecompid = changecompid;
         this.changebillno = changebillno;
         this.changetype = changetype;
         this.changeseqno = changeseqno;
     }
     public DgoodsstockinfoId() {
     }
	public String getChangecompid() {
		return changecompid;
	}
	public void setChangecompid(String changecompid) {
		this.changecompid = changecompid;
	}
	public String getChangebillno() {
		return changebillno;
	}
	public void setChangebillno(String changebillno) {
		this.changebillno = changebillno;
	}
	public String getChangetype() {
		return changetype;
	}
	public void setChangetype(String changetype) {
		this.changetype = changetype;
	}
	public Double getChangeseqno() {
		return changeseqno;
	}
	public void setChangeseqno(Double changeseqno) {
		this.changeseqno = changeseqno;
	}
	
}