package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DgoodsallotmentinfoId  implements java.io.Serializable {


    // Fields    

	 private String entrycompid;
     private String entrybillid;
     private Double allotmentseqno;
     
     public DgoodsallotmentinfoId()
     {
    	 
     }
     public DgoodsallotmentinfoId(String entrycompid, String entrybillid,double allotmentseqno ) {
         this.entrycompid = entrycompid;
         this.entrybillid = entrybillid;
         this.allotmentseqno=allotmentseqno;
     }
	public String getEntrycompid() {
		return entrycompid;
	}
	public void setEntrycompid(String entrycompid) {
		this.entrycompid = entrycompid;
	}
	public String getEntrybillid() {
		return entrybillid;
	}
	public void setEntrybillid(String entrybillid) {
		this.entrybillid = entrybillid;
	}
	public Double getAllotmentseqno() {
		return allotmentseqno;
	}
	public void setAllotmentseqno(Double allotmentseqno) {
		this.allotmentseqno = allotmentseqno;
	}

}