package com.amani.model;



/**
 * Gfm01Id generated by MyEclipse - Hibernate Tools
 */

public class DgoodsbarinfoId  implements java.io.Serializable {


    // Fields    


     private String goodsno;
     private String goodsbarno;

    // Constructors

    /** default constructor */
    public DgoodsbarinfoId() {
    }

    
    /** full constructor */
    public DgoodsbarinfoId(String goodsno, String goodsbarno) {
        this.goodsno = goodsno;
        this.goodsbarno = goodsbarno;
    }


	public String getGoodsno() {
		return goodsno;
	}


	public void setGoodsno(String goodsno) {
		this.goodsno = goodsno;
	}


	public String getGoodsbarno() {
		return goodsbarno;
	}


	public void setGoodsbarno(String goodsbarno) {
		this.goodsbarno = goodsbarno;
	}


   
}