package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DmpackageinfoId  implements java.io.Serializable {


    // Fields    

     private String compid;
     private String packageno;
     private String packageprono;
     
     public DmpackageinfoId(String compid, String packageno,String packageprono ) {
         this.compid = compid;
         this.packageno = packageno;
         this.packageprono=packageprono;
     }
     public DmpackageinfoId() {
     }
	public String getCompid() {
		return compid;
	}
	public void setCompid(String compid) {
		this.compid = compid;
	}
	public String getPackageno() {
		return packageno;
	}
	public void setPackageno(String packageno) {
		this.packageno = packageno;
	}
	public String getPackageprono() {
		return packageprono;
	}
	public void setPackageprono(String packageprono) {
		this.packageprono = packageprono;
	}
	
}