package com.amani.model;

import java.math.BigDecimal;



/**
 * Fex06 generated by MyEclipse - Hibernate Tools
 */

public class Dnointernalcardinfo  implements java.io.Serializable {


    // Fields    

     private DnointernalcardinfoId id;
     private String ineritemno;
     private BigDecimal entrycount;
     private BigDecimal usecount;
     private BigDecimal lastcount;
     private BigDecimal entryamt;
     private BigDecimal useamt;
     private BigDecimal lastamt;
     private BigDecimal costcount;
     private BigDecimal costamt;
     private String entryremark;
     private String ineritemname;
     private String bcardvesting;
     private String bcardno;
     private Double bseqno;
     private String costbillno;
     private String packageNo;//套餐编号
     private Integer ishz;
    // Constructors

    public Integer getIshz() {
		return ishz;
	}

	public void setIshz(Integer ishz) {
		this.ishz = ishz;
	}

	public String getPackageNo() {
		return packageNo;
	}

	public void setPackageNo(String packageNo) {
		this.packageNo = packageNo;
	}

	/** default constructor */
    public Dnointernalcardinfo() {
    }

	/** minimal constructor */
    public Dnointernalcardinfo(DnointernalcardinfoId id) {
        this.id = id;
    }

	public DnointernalcardinfoId getId() {
		return id;
	}

	public void setId(DnointernalcardinfoId id) {
		this.id = id;
	}

	public String getIneritemno() {
		return ineritemno;
	}

	public void setIneritemno(String ineritemno) {
		this.ineritemno = ineritemno;
	}

	public BigDecimal getEntrycount() {
		return entrycount;
	}

	public void setEntrycount(BigDecimal entrycount) {
		this.entrycount = entrycount;
	}

	public BigDecimal getUsecount() {
		return usecount;
	}

	public void setUsecount(BigDecimal usecount) {
		this.usecount = usecount;
	}

	public BigDecimal getLastcount() {
		return lastcount;
	}

	public void setLastcount(BigDecimal lastcount) {
		this.lastcount = lastcount;
	}

	public BigDecimal getEntryamt() {
		return entryamt;
	}

	public void setEntryamt(BigDecimal entryamt) {
		this.entryamt = entryamt;
	}

	public BigDecimal getUseamt() {
		return useamt;
	}

	public void setUseamt(BigDecimal useamt) {
		this.useamt = useamt;
	}

	public BigDecimal getLastamt() {
		return lastamt;
	}

	public void setLastamt(BigDecimal lastamt) {
		this.lastamt = lastamt;
	}

	public String getEntryremark() {
		return entryremark;
	}

	public void setEntryremark(String entryremark) {
		this.entryremark = entryremark;
	}

	public String getIneritemname() {
		return ineritemname;
	}

	public void setIneritemname(String ineritemname) {
		this.ineritemname = ineritemname;
	}

	public String getBcardvesting() {
		return bcardvesting;
	}

	public void setBcardvesting(String bcardvesting) {
		this.bcardvesting = bcardvesting;
	}

	public String getBcardno() {
		return bcardno;
	}

	public void setBcardno(String bcardno) {
		this.bcardno = bcardno;
	}

	public Double getBseqno() {
		return bseqno;
	}

	public void setBseqno(Double bseqno) {
		this.bseqno = bseqno;
	}

	public BigDecimal getCostcount() {
		return costcount;
	}

	public void setCostcount(BigDecimal costcount) {
		this.costcount = costcount;
	}

	public BigDecimal getCostamt() {
		return costamt;
	}

	public void setCostamt(BigDecimal costamt) {
		this.costamt = costamt;
	}

	public String getCostbillno() {
		return costbillno;
	}

	public void setCostbillno(String costbillno) {
		this.costbillno = costbillno;
	}

}