package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DpayinfoId  implements java.io.Serializable {


    // Fields    

     private String paycompid;
     private String paybillid;
     private String paybilltype;
     private Double payseqno;
     
     public DpayinfoId(String paycompid, String paybillid,String paybilltype,double payseqno ) {
         this.paycompid = paycompid;
         this.paybillid = paybillid;
         this.paybilltype= paybilltype;
         this.payseqno=payseqno;
     }
     public DpayinfoId() {
     }
	public String getPaycompid() {
		return paycompid;
	}
	public void setPaycompid(String paycompid) {
		this.paycompid = paycompid;
	}
	public String getPaybillid() {
		return paybillid;
	}
	public void setPaybillid(String paybillid) {
		this.paybillid = paybillid;
	}
	public String getPaybilltype() {
		return paybilltype;
	}
	public void setPaybilltype(String paybilltype) {
		this.paybilltype = paybilltype;
	}
	public Double getPayseqno() {
		return payseqno;
	}
	public void setPayseqno(Double payseqno) {
		this.payseqno = payseqno;
	}
	
}