package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DpayoutinfoId  implements java.io.Serializable {


    // Fields    

     private String payoutcompid;
     private String payoutbillid;
     private double	payoutseqno;
     
     public DpayoutinfoId(String payoutcompid, String payoutbillid ,double	payoutseqno) {
         this.payoutcompid = payoutcompid;
         this.payoutbillid = payoutbillid;
         this.payoutseqno=payoutseqno;
     }
     public DpayoutinfoId() {
     }
	public String getPayoutcompid() {
		return payoutcompid;
	}
	public void setPayoutcompid(String payoutcompid) {
		this.payoutcompid = payoutcompid;
	}
	public String getPayoutbillid() {
		return payoutbillid;
	}
	public void setPayoutbillid(String payoutbillid) {
		this.payoutbillid = payoutbillid;
	}
	public double getPayoutseqno() {
		return payoutseqno;
	}
	public void setPayoutseqno(double payoutseqno) {
		this.payoutseqno = payoutseqno;
	}
}