package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DproexchangeinfobyproId  implements java.io.Serializable {


    // Fields    

     private String changecompid;
     private String changebillid;
     private Double changeseqno;
     
     public DproexchangeinfobyproId(String changecompid, String changebillid,double changeseqno ) {
         this.changecompid = changecompid;
         this.changebillid = changebillid;
         this.changeseqno=changeseqno;
     }
     public DproexchangeinfobyproId() {
     }
	public String getChangecompid() {
		return changecompid;
	}
	public void setChangecompid(String changecompid) {
		this.changecompid = changecompid;
	}
	public String getChangebillid() {
		return changebillid;
	}
	public void setChangebillid(String changebillid) {
		this.changebillid = changebillid;
	}
	public Double getChangeseqno() {
		return changeseqno;
	}
	public void setChangeseqno(Double changeseqno) {
		this.changeseqno = changeseqno;
	}
	
}