package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DsalecardproinfoId  implements java.io.Serializable {


    // Fields    

     private String salecompid;
     private String salebillid;
     private Integer salebilltype;
     private Double seleproseqno;
     
     public DsalecardproinfoId(String salecompid, String salebillid,int salebilltype,double seleproseqno ) {
         this.salecompid = salecompid;
         this.salebillid = salebillid;
         this.salebilltype = salebilltype;
         this.seleproseqno=seleproseqno;
     }
     public DsalecardproinfoId() {
     }
	public String getSalecompid() {
		return salecompid;
	}
	public void setSalecompid(String salecompid) {
		this.salecompid = salecompid;
	}
	public String getSalebillid() {
		return salebillid;
	}
	public void setSalebillid(String salebillid) {
		this.salebillid = salebillid;
	}
	public Double getSeleproseqno() {
		return seleproseqno;
	}
	public void setSeleproseqno(Double seleproseqno) {
		this.seleproseqno = seleproseqno;
	}
	public Integer getSalebilltype() {
		return salebilltype;
	}
	public void setSalebilltype(Integer salebilltype) {
		this.salebilltype = salebilltype;
	}
	
}