package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DsalebarcodecardinfoId  implements java.io.Serializable {


    // Fields    

     private String salecompid;
     private String salebillid;
     private Double saleseqno;
     
     public DsalebarcodecardinfoId(String salecompid, String salebillid,double saleseqno ) {
         this.salecompid = salecompid;
         this.salebillid = salebillid;
         this.saleseqno=saleseqno;
     }
     public DsalebarcodecardinfoId() {
     }
	public String getSalecompid() {
		return salecompid;
	}
	public void setSalecompid(String salecompid) {
		this.salecompid = salecompid;
	}
	public String getSalebillid() {
		return salebillid;
	}
	public void setSalebillid(String salebillid) {
		this.salebillid = salebillid;
	}
	public Double getSaleseqno() {
		return saleseqno;
	}
	public void setSaleseqno(Double saleseqno) {
		this.saleseqno = saleseqno;
	}

	
	
}