package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class DstafftargetinfoId  implements java.io.Serializable {


    // Fields    

     private String entrycompid;
     private String entrybillid;
     private Double	entryseqno;
   
     
     public Double getEntryseqno() {
		return entryseqno;
	}
	public void setEntryseqno(Double entryseqno) {
		this.entryseqno = entryseqno;
	}
	public DstafftargetinfoId(String entrycompid, String entrybillid ,double entryseqno) {
         this.entrycompid = entrycompid;
         this.entrybillid = entrybillid;
         this.entryseqno=entryseqno;
     }
     public DstafftargetinfoId() {
     }
	public String getEntrycompid() {
		return entrycompid;
	}
	public void setEntrycompid(String entrycompid) {
		this.entrycompid = entrycompid;
	}
	public String getEntrybillid() {
		return entrybillid;
	}
	public void setEntrybillid(String entrybillid) {
		this.entrybillid = entrybillid;
	}

	
	
}