package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class McardallotmentId  implements java.io.Serializable {


    // Fields    

     private String callotcompid;
     private String callotbillid;
   
     
     public McardallotmentId(String callotcompid, String callotbillid ) {
         this.callotcompid = callotcompid;
         this.callotbillid = callotbillid;
     }
     public McardallotmentId() {
     }
	public String getCallotcompid() {
		return callotcompid;
	}
	public void setCallotcompid(String callotcompid) {
		this.callotcompid = callotcompid;
	}
	public String getCallotbillid() {
		return callotbillid;
	}
	public void setCallotbillid(String callotbillid) {
		this.callotbillid = callotbillid;
	}
	
}