package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class McardchangeinfoId  implements java.io.Serializable {


    // Fields    

     private String changecompid;
     private String changebillid;
     private Integer changetype;
     
     public String getChangecompid() {
		return changecompid;
	}
	public void setChangecompid(String changecompid) {
		this.changecompid = changecompid;
	}
	public String getChangebillid() {
		return changebillid;
	}
	public void setChangebillid(String changebillid) {
		this.changebillid = changebillid;
	}
	public McardchangeinfoId(String changecompid, String changebillid ,int changetype) {
         this.changecompid = changecompid;
         this.changebillid = changebillid;
         this.changetype=changetype;
     }
     public McardchangeinfoId() {
     }
	public Integer getChangetype() {
		return changetype;
	}
	public void setChangetype(Integer changetype) {
		this.changetype = changetype;
	}
	
}