package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class McardnoinsertId  implements java.io.Serializable {


    // Fields    

     private String cinsertcompid;
     private String cinsertbillid;
   
     
     public McardnoinsertId(String cinsertcompid, String cinsertbillid ) {
         this.cinsertcompid = cinsertcompid;
         this.cinsertbillid = cinsertbillid;
     }
     public McardnoinsertId() {
     }
	public String getCinsertcompid() {
		return cinsertcompid;
	}
	public void setCinsertcompid(String cinsertcompid) {
		this.cinsertcompid = cinsertcompid;
	}
	public String getCinsertbillid() {
		return cinsertbillid;
	}
	public void setCinsertbillid(String cinsertbillid) {
		this.cinsertbillid = cinsertbillid;
	}
	
	
}