package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class McardapponlineId  implements java.io.Serializable {


    // Fields    

     private String cappcompid;
     private String cappcompbillid;
   
     
     public McardapponlineId(String cappcompid, String cappcompbillid ) {
         this.cappcompid = cappcompid;
         this.cappcompbillid = cappcompbillid;
     }
     public McardapponlineId() {
     }
	public String getCappcompid() {
		return cappcompid;
	}
	public void setCappcompid(String cappcompid) {
		this.cappcompid = cappcompid;
	}
	public String getCappcompbillid() {
		return cappcompbillid;
	}
	public void setCappcompbillid(String cappcompbillid) {
		this.cappcompbillid = cappcompbillid;
	}
	
}