package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class MconsumeinfoId  implements java.io.Serializable {


    // Fields    

     private String cscompid;
     private String csbillid;
   
     
     public MconsumeinfoId(String cscompid, String csbillid ) {
         this.cscompid = cscompid;
         this.csbillid = csbillid;
     }
     public MconsumeinfoId() {
     }
	public String getCscompid() {
		return cscompid;
	}
	public void setCscompid(String cscompid) {
		this.cscompid = cscompid;
	}
	public String getCsbillid() {
		return csbillid;
	}
	public void setCsbillid(String csbillid) {
		this.csbillid = csbillid;
	}
	
	
}