package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class MemberinfoId  implements java.io.Serializable {


    // Fields    

     private String membervesting;
     private String memberno;

     
   
	public MemberinfoId(String membervesting, String memberno ) {
         this.membervesting = membervesting;
         this.memberno = memberno;
     }
     public MemberinfoId() {
     }
	public String getMembervesting() {
		return membervesting;
	}
	public void setMembervesting(String membervesting) {
		this.membervesting = membervesting;
	}
	public String getMemberno() {
		return memberno;
	}
	public void setMemberno(String memberno) {
		this.memberno = memberno;
	}
	
	
}