package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class MgoodssendinfoId  implements java.io.Serializable {


    // Fields    

     private String sendcompid;
     private String sendbillid;
   
     
     public MgoodssendinfoId(String sendcompid, String sendbillid ) {
         this.sendcompid = sendcompid;
         this.sendbillid = sendbillid;
     }
     public MgoodssendinfoId() {
     }
	public String getSendcompid() {
		return sendcompid;
	}
	public void setSendcompid(String sendcompid) {
		this.sendcompid = sendcompid;
	}
	public String getSendbillid() {
		return sendbillid;
	}
	public void setSendbillid(String sendbillid) {
		this.sendbillid = sendbillid;
	}
	
}