package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class MgoodsorderinfoId  implements java.io.Serializable {


    // Fields    

     private String ordercompid;
     private String orderbillid;
   
     
     public MgoodsorderinfoId(String ordercompid, String orderbillid ) {
         this.ordercompid = ordercompid;
         this.orderbillid = orderbillid;
     }
     public MgoodsorderinfoId() {
     }
	public String getOrdercompid() {
		return ordercompid;
	}
	public void setOrdercompid(String ordercompid) {
		this.ordercompid = ordercompid;
	}
	public String getOrderbillid() {
		return orderbillid;
	}
	public void setOrderbillid(String orderbillid) {
		this.orderbillid = orderbillid;
	}
	
}