package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class MgoodsinsertId  implements java.io.Serializable {


    // Fields    

     private String insercompid;
     private String inserbillid;
   
     
     public MgoodsinsertId(String insercompid, String inserbillid ) {
         this.insercompid = insercompid;
         this.inserbillid = inserbillid;
     }
     public MgoodsinsertId() {
     }
	public String getInsercompid() {
		return insercompid;
	}
	public void setInsercompid(String insercompid) {
		this.insercompid = insercompid;
	}
	public String getInserbillid() {
		return inserbillid;
	}
	public void setInserbillid(String inserbillid) {
		this.inserbillid = inserbillid;
	}

	
	
}