package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class MgoodsstockinfoId  implements java.io.Serializable {


    // Fields    

     private String changecompid;
     private String changebillno;
     private String changetype;
     
     public MgoodsstockinfoId(String changecompid, String changebillno,String changetype ) {
         this.changecompid = changecompid;
         this.changebillno = changebillno;
         this.changetype = changetype;
     }
     public MgoodsstockinfoId() {
     }
	public String getChangecompid() {
		return changecompid;
	}
	public void setChangecompid(String changecompid) {
		this.changecompid = changecompid;
	}
	public String getChangebillno() {
		return changebillno;
	}
	public void setChangebillno(String changebillno) {
		this.changebillno = changebillno;
	}
	public String getChangetype() {
		return changetype;
	}
	public void setChangetype(String changetype) {
		this.changetype = changetype;
	}
	
}