package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class MgoodsreceiptId  implements java.io.Serializable {


    // Fields    

     private String receiptcompid;
     private String receiptbillid;
   
     
     public MgoodsreceiptId(String receiptcompid, String receiptbillid ) {
         this.receiptcompid = receiptcompid;
         this.receiptbillid = receiptbillid;
     }
     public MgoodsreceiptId() {
     }
	public String getReceiptcompid() {
		return receiptcompid;
	}
	public void setReceiptcompid(String receiptcompid) {
		this.receiptcompid = receiptcompid;
	}
	public String getReceiptbillid() {
		return receiptbillid;
	}
	public void setReceiptbillid(String receiptbillid) {
		this.receiptbillid = receiptbillid;
	}
	
}