package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class MgoodsinventoryId  implements java.io.Serializable {


    // Fields    

     private String inventcompid;
     private String inventbillid;
   
     
     public MgoodsinventoryId(String inventcompid, String inventbillid ) {
         this.inventcompid = inventcompid;
         this.inventbillid = inventbillid;
     }
     public MgoodsinventoryId() {
     }
	public String getInventcompid() {
		return inventcompid;
	}
	public void setInventcompid(String inventcompid) {
		this.inventcompid = inventcompid;
	}
	public String getInventbillid() {
		return inventbillid;
	}
	public void setInventbillid(String inventbillid) {
		this.inventbillid = inventbillid;
	}
}