package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class MgoodsouterId  implements java.io.Serializable {


    // Fields    

     private String outercompid;
     private String outerbillid;
   
     
     public MgoodsouterId(String outercompid, String outerbillid ) {
         this.outercompid = outercompid;
         this.outerbillid = outerbillid;
     }
     public MgoodsouterId() {
     }
	public String getOutercompid() {
		return outercompid;
	}
	public void setOutercompid(String outercompid) {
		this.outercompid = outercompid;
	}
	public String getOuterbillid() {
		return outerbillid;
	}
	public void setOuterbillid(String outerbillid) {
		this.outerbillid = outerbillid;
	}

	
	
}