package com.amani.model;




/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class MgoodsallotmentinfoId  implements java.io.Serializable {


    // Fields    

     private String entrycompid;
     private String entrybillid;
   
     
     public MgoodsallotmentinfoId(String entrycompid, String entrybillid ) {
         this.entrycompid = entrycompid;
         this.entrybillid = entrybillid;
     }
     public MgoodsallotmentinfoId() {
     }
	public String getEntrycompid() {
		return entrycompid;
	}
	public void setEntrycompid(String entrycompid) {
		this.entrycompid = entrycompid;
	}
	public String getEntrybillid() {
		return entrybillid;
	}
	public void setEntrybillid(String entrybillid) {
		this.entrybillid = entrybillid;
	}
}