package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class MpackageinfoId  implements java.io.Serializable {


    // Fields    

     private String compid;
     private String packageno;
   
     
     public MpackageinfoId(String compid, String packageno ) {
         this.compid = compid;
         this.packageno = packageno;
     }
     public MpackageinfoId() {
     }
	public String getCompid() {
		return compid;
	}
	public void setCompid(String compid) {
		this.compid = compid;
	}
	public String getPackageno() {
		return packageno;
	}
	public void setPackageno(String packageno) {
		this.packageno = packageno;
	}
	
}