package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class MpayoutinfoId  implements java.io.Serializable {


    // Fields    

     private String payoutcompid;
     private String payoutbillid;
   
     
     public MpayoutinfoId(String payoutcompid, String payoutbillid ) {
         this.payoutcompid = payoutcompid;
         this.payoutbillid = payoutbillid;
     }
     public MpayoutinfoId() {
     }
	public String getPayoutcompid() {
		return payoutcompid;
	}
	public void setPayoutcompid(String payoutcompid) {
		this.payoutcompid = payoutcompid;
	}
	public String getPayoutbillid() {
		return payoutbillid;
	}
	public void setPayoutbillid(String payoutbillid) {
		this.payoutbillid = payoutbillid;
	}

	
}