package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class MreturngoodsinfoId  implements java.io.Serializable {


    // Fields    

     private String returncompid;
     private String returnbillid;
   
     
     public MreturngoodsinfoId(String returncompid, String returnbillid ) {
         this.returncompid = returncompid;
         this.returnbillid = returnbillid;
     }
     public MreturngoodsinfoId() {
     }
	public String getReturncompid() {
		return returncompid;
	}
	public void setReturncompid(String returncompid) {
		this.returncompid = returncompid;
	}
	public String getReturnbillid() {
		return returnbillid;
	}
	public void setReturnbillid(String returnbillid) {
		this.returnbillid = returnbillid;
	}
}