package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class MsalecardinfoId  implements java.io.Serializable {


    // Fields    

     private String salecompid;
     private String salebillid;
   
     
     public MsalecardinfoId(String salecompid, String salebillid ) {
         this.salecompid = salecompid;
         this.salebillid = salebillid;
     }
     public MsalecardinfoId() {
     }
	public String getSalecompid() {
		return salecompid;
	}
	public void setSalecompid(String salecompid) {
		this.salecompid = salecompid;
	}
	public String getSalebillid() {
		return salebillid;
	}
	public void setSalebillid(String salebillid) {
		this.salebillid = salebillid;
	}

}