package com.amani.model;

import java.math.BigDecimal;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class MstafftargetinfoId  implements java.io.Serializable {


    // Fields    

     private String entrycompid;
     private String entrybillid;
   
     
     public MstafftargetinfoId(String entrycompid, String entrybillid ) {
         this.entrycompid = entrycompid;
         this.entrybillid = entrybillid;
     }
     public MstafftargetinfoId() {
     }
	public String getEntrycompid() {
		return entrycompid;
	}
	public void setEntrycompid(String entrycompid) {
		this.entrycompid = entrycompid;
	}
	public String getEntrybillid() {
		return entrybillid;
	}
	public void setEntrybillid(String entrybillid) {
		this.entrybillid = entrybillid;
	}

	
	
}