package com.amani.model;

import java.math.BigDecimal;



/**
 * Gxm08 generated by MyEclipse - Hibernate Tools
 */

public class Sendpointcard  implements java.io.Serializable {


    // Fields    

     private SendpointcardId id;
     private String senddate;
     private String sendempid;
     private String sourcebillid;
     private String sourcecardno;
     private String sourcecardtype;
     private String sourcedate;
     private  BigDecimal sourceamt;
     private String sendcardno;
     private  BigDecimal sendamt;
     private String sendmark;
     private String operation;
     private String membername;
     private String memberphone;
     private Integer sendrateflag;
     private Integer sendpicflag;
     private String picno;
     private String firstdateno;
     private String bsendcompid;
     private String bsendbillid;
     private Integer bsendtype;
     private Integer createcardtype;
     private Integer createcardcount;
     private String sendtypeText;
     private double changeseqno;
    // Constructors

    public double getChangeseqno() {
		return changeseqno;
	}

	public void setChangeseqno(double changeseqno) {
		this.changeseqno = changeseqno;
	}

	/** default constructor */
    public Sendpointcard() {
    }

	/** minimal constructor */
    public Sendpointcard(SendpointcardId id) {
        this.id = id;
    }

	public SendpointcardId getId() {
		return id;
	}

	public void setId(SendpointcardId id) {
		this.id = id;
	}

	public String getSenddate() {
		return senddate;
	}

	public void setSenddate(String senddate) {
		this.senddate = senddate;
	}

	public String getSendempid() {
		return sendempid;
	}

	public void setSendempid(String sendempid) {
		this.sendempid = sendempid;
	}

	public String getSourcebillid() {
		return sourcebillid;
	}

	public void setSourcebillid(String sourcebillid) {
		this.sourcebillid = sourcebillid;
	}

	public String getSourcecardno() {
		return sourcecardno;
	}

	public void setSourcecardno(String sourcecardno) {
		this.sourcecardno = sourcecardno;
	}

	public String getSourcedate() {
		return sourcedate;
	}

	public void setSourcedate(String sourcedate) {
		this.sourcedate = sourcedate;
	}


	public String getSendcardno() {
		return sendcardno;
	}

	public void setSendcardno(String sendcardno) {
		this.sendcardno = sendcardno;
	}

	
	public BigDecimal getSourceamt() {
		return sourceamt;
	}

	public void setSourceamt(BigDecimal sourceamt) {
		this.sourceamt = sourceamt;
	}

	public BigDecimal getSendamt() {
		return sendamt;
	}

	public void setSendamt(BigDecimal sendamt) {
		this.sendamt = sendamt;
	}

	public String getSendmark() {
		return sendmark;
	}

	public void setSendmark(String sendmark) {
		this.sendmark = sendmark;
	}

	public String getOperation() {
		return operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	public String getMembername() {
		return membername;
	}

	public void setMembername(String membername) {
		this.membername = membername;
	}

	public String getMemberphone() {
		return memberphone;
	}

	public void setMemberphone(String memberphone) {
		this.memberphone = memberphone;
	}

	public Integer getSendrateflag() {
		return sendrateflag;
	}

	public void setSendrateflag(Integer sendrateflag) {
		this.sendrateflag = sendrateflag;
	}

	public Integer getSendpicflag() {
		return sendpicflag;
	}

	public void setSendpicflag(Integer sendpicflag) {
		this.sendpicflag = sendpicflag;
	}

	public String getPicno() {
		return picno;
	}

	public void setPicno(String picno) {
		this.picno = picno;
	}

	public String getBsendcompid() {
		return bsendcompid;
	}

	public void setBsendcompid(String bsendcompid) {
		this.bsendcompid = bsendcompid;
	}

	public String getBsendbillid() {
		return bsendbillid;
	}

	public void setBsendbillid(String bsendbillid) {
		this.bsendbillid = bsendbillid;
	}

	public Integer getBsendtype() {
		return bsendtype;
	}

	public void setBsendtype(Integer bsendtype) {
		this.bsendtype = bsendtype;
	}

	public String getSendtypeText() {
		return sendtypeText;
	}

	public void setSendtypeText(String sendtypeText) {
		this.sendtypeText = sendtypeText;
	}

	public String getSourcecardtype() {
		return sourcecardtype;
	}

	public void setSourcecardtype(String sourcecardtype) {
		this.sourcecardtype = sourcecardtype;
	}

	public String getFirstdateno() {
		return firstdateno;
	}

	public void setFirstdateno(String firstdateno) {
		this.firstdateno = firstdateno;
	}

	public Integer getCreatecardtype() {
		return createcardtype;
	}

	public void setCreatecardtype(Integer createcardtype) {
		this.createcardtype = createcardtype;
	}

	public Integer getCreatecardcount() {
		return createcardcount;
	}

	public void setCreatecardcount(Integer createcardcount) {
		this.createcardcount = createcardcount;
	}
  
}