package com.amani.model;

import java.math.BigDecimal;



/**
 * Ham12 generated by MyEclipse - Hibernate Tools
 */

public class Staffhistory  implements java.io.Serializable {


    // Fields    

     private Integer 		seqno;
     private String 		manageno;
     private String 		changetype;
     private String 		oldcompid;
     private String 		oldempid;
     private String 		olddepid;
     private String 		oldpostion;
     private BigDecimal 	oldsalary;
     private String 		oldyjtype;
     private BigDecimal 	oldyjrate;    
     private BigDecimal     oldyjamt;
     private String 		newcompid;
     private String 		newempid;
     private String 		newdepid;
     private String 		newpostion;
     private BigDecimal 	newsalary;
     private String 		newyjtype;
     private BigDecimal 	newyjrate;
     private BigDecimal 	newyjramt;
     private String 		effectivedate;
     private String 		optionbill;
     private String 		changemark;
	public Integer getSeqno() {
		return seqno;
	}
	public void setSeqno(Integer seqno) {
		this.seqno = seqno;
	}
	public String getManageno() {
		return manageno;
	}
	public void setManageno(String manageno) {
		this.manageno = manageno;
	}
	public String getChangetype() {
		return changetype;
	}
	public void setChangetype(String changetype) {
		this.changetype = changetype;
	}
	public String getOldcompid() {
		return oldcompid;
	}
	public void setOldcompid(String oldcompid) {
		this.oldcompid = oldcompid;
	}
	public String getOldempid() {
		return oldempid;
	}
	public void setOldempid(String oldempid) {
		this.oldempid = oldempid;
	}
	public String getOlddepid() {
		return olddepid;
	}
	public void setOlddepid(String olddepid) {
		this.olddepid = olddepid;
	}
	public String getOldpostion() {
		return oldpostion;
	}
	public void setOldpostion(String oldpostion) {
		this.oldpostion = oldpostion;
	}
	public BigDecimal getOldsalary() {
		return oldsalary;
	}
	public void setOldsalary(BigDecimal oldsalary) {
		this.oldsalary = oldsalary;
	}
	public String getOldyjtype() {
		return oldyjtype;
	}
	public void setOldyjtype(String oldyjtype) {
		this.oldyjtype = oldyjtype;
	}

	public String getNewcompid() {
		return newcompid;
	}
	public void setNewcompid(String newcompid) {
		this.newcompid = newcompid;
	}
	public String getNewempid() {
		return newempid;
	}
	public void setNewempid(String newempid) {
		this.newempid = newempid;
	}

	public String getNewdepid() {
		return newdepid;
	}
	public void setNewdepid(String newdepid) {
		this.newdepid = newdepid;
	}
	public String getNewpostion() {
		return newpostion;
	}
	public void setNewpostion(String newpostion) {
		this.newpostion = newpostion;
	}
	public BigDecimal getNewsalary() {
		return newsalary;
	}
	public void setNewsalary(BigDecimal newsalary) {
		this.newsalary = newsalary;
	}
	public String getNewyjtype() {
		return newyjtype;
	}
	public void setNewyjtype(String newyjtype) {
		this.newyjtype = newyjtype;
	}

	public BigDecimal getOldyjrate() {
		return oldyjrate;
	}
	public void setOldyjrate(BigDecimal oldyjrate) {
		this.oldyjrate = oldyjrate;
	}
	public BigDecimal getNewyjrate() {
		return newyjrate;
	}
	public void setNewyjrate(BigDecimal newyjrate) {
		this.newyjrate = newyjrate;
	}
	public String getEffectivedate() {
		return effectivedate;
	}
	public void setEffectivedate(String effectivedate) {
		this.effectivedate = effectivedate;
	}
	public String getOptionbill() {
		return optionbill;
	}
	public void setOptionbill(String optionbill) {
		this.optionbill = optionbill;
	}
	public BigDecimal getOldyjamt() {
		return oldyjamt;
	}
	public void setOldyjamt(BigDecimal oldyjamt) {
		this.oldyjamt = oldyjamt;
	}
	public BigDecimal getNewyjramt() {
		return newyjramt;
	}
	public void setNewyjramt(BigDecimal newyjramt) {
		this.newyjramt = newyjramt;
	}
	public String getChangemark() {
		return changemark;
	}
	public void setChangemark(String changemark) {
		this.changemark = changemark;
	}
	

}