package com.amani.model;
/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class StaffchangeinfoId  implements java.io.Serializable {


    // Fields    

     private String changecompid;
     private String changebillid;
     private Integer changetype;
     
     public StaffchangeinfoId(String changecompid, String changebillid,int changetype) {
         this.changecompid = changecompid;
         this.changebillid = changebillid;
         this.changetype= changetype;
     }
     public StaffchangeinfoId() {
     }
	public String getChangecompid() {
		return changecompid;
	}
	public void setChangecompid(String changecompid) {
		this.changecompid = changecompid;
	}
	public String getChangebillid() {
		return changebillid;
	}
	public void setChangebillid(String changebillid) {
		this.changebillid = changebillid;
	}
	public Integer getChangetype() {
		return changetype;
	}
	public void setChangetype(Integer changetype) {
		this.changetype = changetype;
	}
}