package com.amani.model;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class StaffinfoId  implements java.io.Serializable {


    // Fields    

     private String compno;
     private String staffno;
 
     
     public StaffinfoId(String compno, String staffno ) {
         this.compno = compno;
         this.staffno = staffno;
     }
     public StaffinfoId() {
     }
	public String getCompno() {
		return compno;
	}
	public void setCompno(String compno) {
		this.compno = compno;
	}
	public String getStaffno() {
		return staffno;
	}
	public void setStaffno(String staffno) {
		this.staffno = staffno;
	}
	

}