package com.amani.model;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class StoreflowinfoId  implements java.io.Serializable {


    // Fields    

     private String compid;
     private String billid;
    
     public StoreflowinfoId(String compid, String billid ) {
         this.compid = compid;
         this.billid = billid;
     }
     public StoreflowinfoId() {
     }
	public String getCompid() {
		return compid;
	}
	public void setCompid(String compid) {
		this.compid = compid;
	}
	public String getBillid() {
		return billid;
	}
	public void setBillid(String billid) {
		this.billid = billid;
	}
	
}