package com.amani.model;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class SysmodeinfoId  implements java.io.Serializable {


    // Fields    

     private String sysversion;
     private String upmoduleno;
     private String curmoduleno;


    // Constructors

    /** default constructor */
    public SysmodeinfoId() {
    }

    
    /** full constructor */
    public SysmodeinfoId(String sysversion, String upmoduleno,String curmoduleno) {
        this.sysversion = sysversion;
        this.upmoduleno = upmoduleno;
        this.curmoduleno = curmoduleno;
    }


	public String getSysversion() {
		return sysversion;
	}


	public void setSysversion(String sysversion) {
		this.sysversion = sysversion;
	}


	public String getUpmoduleno() {
		return upmoduleno;
	}


	public void setUpmoduleno(String upmoduleno) {
		this.upmoduleno = upmoduleno;
	}


	public String getCurmoduleno() {
		return curmoduleno;
	}


	public void setCurmoduleno(String curmoduleno) {
		this.curmoduleno = curmoduleno;
	}

  


}