package com.amani.model;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class SysmodepurviewId  implements java.io.Serializable {


    // Fields    

     private String curRoleno;
     private String curpurviewno;


    // Constructors

    /** default constructor */
    public SysmodepurviewId() {
    }

    
    /** full constructor */
    public SysmodepurviewId(String curRoleno, String curpurviewno) {
        this.curRoleno = curRoleno;
        this.curpurviewno = curpurviewno;
    }


	public String getCurRoleno() {
		return curRoleno;
	}


	public void setCurRoleno(String curRoleno) {
		this.curRoleno = curRoleno;
	}


	public String getCurpurviewno() {
		return curpurviewno;
	}


	public void setCurpurviewno(String curpurviewno) {
		this.curpurviewno = curpurviewno;
	}



}