package com.amani.model;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class SysparaminfoId  implements java.io.Serializable {


    // Fields    

     private String compid;
     private String paramid;
 


    // Constructors

    /** default constructor */
    public SysparaminfoId() {
    }

    
    /** full constructor */
    public SysparaminfoId(String compid, String paramid) {
        this.compid = compid;
        this.paramid = paramid;
      
    }


	public String getCompid() {
		return compid;
	}


	public void setCompid(String compid) {
		this.compid = compid;
	}


	public String getParamid() {
		return paramid;
	}


	public void setParamid(String paramid) {
		this.paramid = paramid;
	}



}