package com.amani.model;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class SysrolemodeId  implements java.io.Serializable {


    // Fields    

     private String roleno;
     private String sysmodeno;
     private String functionno;


    // Constructors

    /** default constructor */
    public SysrolemodeId() {
    }

    
    /** full constructor */
    public SysrolemodeId(String roleno, String sysmodeno,String functionno) {
        this.roleno = roleno;
        this.sysmodeno = sysmodeno;
        this.functionno = functionno;
    }

   

public String getRoleno() {
	return roleno;
}


public void setRoleno(String roleno) {
	this.roleno = roleno;
}


public String getSysmodeno() {
	return sysmodeno;
}


public void setSysmodeno(String sysmodeno) {
	this.sysmodeno = sysmodeno;
}


public String getFunctionno() {
	return functionno;
}


public void setFunctionno(String functionno) {
	this.functionno = functionno;
}   





}