package com.amani.model;



/**
 * PapercardId generated by MyEclipse - Hibernate Tools
 */

public class UsereditrightId  implements java.io.Serializable {


    // Fields    

     private String userno;
     private String sysmodeno;
     private String functionno;


    // Constructors

    /** default constructor */
    public UsereditrightId() {
    }

    
    /** full constructor */
    public UsereditrightId(String userno, String sysmodeno,String functionno) {
        this.userno = userno;
        this.sysmodeno = sysmodeno;
        this.functionno = functionno;
    }

   




public String getUserno() {
		return userno;
	}


	public void setUserno(String userno) {
		this.userno = userno;
	}


public String getSysmodeno() {
	return sysmodeno;
}


public void setSysmodeno(String sysmodeno) {
	this.sysmodeno = sysmodeno;
}


public String getFunctionno() {
	return functionno;
}


public void setFunctionno(String functionno) {
	this.functionno = functionno;
}   





}