package com.amani.old.model;

/**
 * Gbm01 generated by MyEclipse - Hibernate Tools
 */

public class Gbm01 implements java.io.Serializable {


    // Fields    

     private Gbm01Id id;
     private String gba02c;
     private String gba03c;
     private String gba04c;
     private String gba05c;
     private String gba06c;
     private String gba07c;
     private String gba08c;
     private String gba09c;
     private String gba10c;
     private String gba11c;
     private String gba12c;
     private String gba13c;
     private Integer gba14i;
     private String gba15c;
     private String gba16c;
     private String gba17d;
     private String gba18c;
     private String gba19c;
     private String gba20c;
     private String gba21c;
     private String gba22c;
     private String gba23c;
     private String gba24c;
     private String gba25c;
     private String gba26c;
     private String gba27c;
     private Integer gba28i;
     private String gba29c;
     private String gba30c;
     private String gba31c;
     private String gba32c;
     private String gba33c;
     private String gba34c;
     private String gba35c;
     private String gba36c;
     private String gba37c;
     private String gba38c;
     private Integer gba39i;
     private String gba40c;
     private String gba41c;


    // Constructors

    /** default constructor */
    public Gbm01() {
    }

	/** minimal constructor */
    public Gbm01(Gbm01Id id) {
        this.id = id;
    }
    
    /** full constructor */
    public Gbm01(Gbm01Id id, String gba02c, String gba03c, String gba04c, String gba05c, String gba06c, String gba07c, String gba08c, String gba09c, String gba10c, String gba11c, String gba12c, String gba13c, Integer gba14i, String gba15c, String gba16c, String gba17d, String gba18c, String gba19c, String gba20c, String gba21c, String gba22c, String gba23c, String gba24c, String gba25c, String gba26c, String gba27c, Integer gba28i, String gba29c, String gba30c, String gba31c, String gba32c, String gba33c, String gba34c, String gba35c, String gba36c, String gba37c, String gba38c, Integer gba39i, String gba40c ) {
        this.id = id;
        this.gba02c = gba02c;
        this.gba03c = gba03c;
        this.gba04c = gba04c;
        this.gba05c = gba05c;
        this.gba06c = gba06c;
        this.gba07c = gba07c;
        this.gba08c = gba08c;
        this.gba09c = gba09c;
        this.gba10c = gba10c;
        this.gba11c = gba11c;
        this.gba12c = gba12c;
        this.gba13c = gba13c;
        this.gba14i = gba14i;
        this.gba15c = gba15c;
        this.gba16c = gba16c;
        this.gba17d = gba17d;
        this.gba18c = gba18c;
        this.gba19c = gba19c;
        this.gba20c = gba20c;
        this.gba21c = gba21c;
        this.gba22c = gba22c;
        this.gba23c = gba23c;
        this.gba24c = gba24c;
        this.gba25c = gba25c;
        this.gba26c = gba26c;
        this.gba27c = gba27c;
        this.gba28i = gba28i;
        this.gba29c = gba29c;
        this.gba30c = gba30c;
        this.gba31c = gba31c;
        this.gba32c = gba32c;
        this.gba33c = gba33c;
        this.gba34c = gba34c;
        this.gba35c = gba35c;
        this.gba36c = gba36c;
        this.gba37c = gba37c;
        this.gba38c = gba38c;
        this.gba39i = gba39i;
        this.gba40c = gba40c;
     
    }

   
    // Property accessors

    public Gbm01Id getId() {
        return this.id;
    }
    
    public void setId(Gbm01Id id) {
        this.id = id;
    }

    public String getGba02c() {
        return this.gba02c;
    }
    
    public void setGba02c(String gba02c) {
        this.gba02c = gba02c;
    }

    public String getGba03c() {
        return this.gba03c;
    }
    
    public void setGba03c(String gba03c) {
        this.gba03c = gba03c;
    }

    public String getGba04c() {
        return this.gba04c;
    }
    
    public void setGba04c(String gba04c) {
        this.gba04c = gba04c;
    }

    public String getGba05c() {
        return this.gba05c;
    }
    
    public void setGba05c(String gba05c) {
        this.gba05c = gba05c;
    }

    public String getGba06c() {
        return this.gba06c;
    }
    
    public void setGba06c(String gba06c) {
        this.gba06c = gba06c;
    }

    public String getGba07c() {
        return this.gba07c;
    }
    
    public void setGba07c(String gba07c) {
        this.gba07c = gba07c;
    }

    public String getGba08c() {
        return this.gba08c;
    }
    
    public void setGba08c(String gba08c) {
        this.gba08c = gba08c;
    }

    public String getGba09c() {
        return this.gba09c;
    }
    
    public void setGba09c(String gba09c) {
        this.gba09c = gba09c;
    }

    public String getGba10c() {
        return this.gba10c;
    }
    
    public void setGba10c(String gba10c) {
        this.gba10c = gba10c;
    }

    public String getGba11c() {
        return this.gba11c;
    }
    
    public void setGba11c(String gba11c) {
        this.gba11c = gba11c;
    }

    public String getGba12c() {
        return this.gba12c;
    }
    
    public void setGba12c(String gba12c) {
        this.gba12c = gba12c;
    }

    public String getGba13c() {
        return this.gba13c;
    }
    
    public void setGba13c(String gba13c) {
        this.gba13c = gba13c;
    }

    public Integer getGba14i() {
        return this.gba14i;
    }
    
    public void setGba14i(Integer gba14i) {
        this.gba14i = gba14i;
    }

    public String getGba15c() {
        return this.gba15c;
    }
    
    public void setGba15c(String gba15c) {
        this.gba15c = gba15c;
    }

    public String getGba16c() {
        return this.gba16c;
    }
    
    public void setGba16c(String gba16c) {
        this.gba16c = gba16c;
    }

    public String getGba17d() {
        return this.gba17d;
    }
    
    public void setGba17d(String gba17d) {
        this.gba17d = gba17d;
    }

    public String getGba18c() {
        return this.gba18c;
    }
    
    public void setGba18c(String gba18c) {
        this.gba18c = gba18c;
    }

    public String getGba19c() {
        return this.gba19c;
    }
    
    public void setGba19c(String gba19c) {
        this.gba19c = gba19c;
    }

    public String getGba20c() {
        return this.gba20c;
    }
    
    public void setGba20c(String gba20c) {
        this.gba20c = gba20c;
    }

    public String getGba21c() {
        return this.gba21c;
    }
    
    public void setGba21c(String gba21c) {
        this.gba21c = gba21c;
    }

    public String getGba22c() {
        return this.gba22c;
    }
    
    public void setGba22c(String gba22c) {
        this.gba22c = gba22c;
    }

    public String getGba23c() {
        return this.gba23c;
    }
    
    public void setGba23c(String gba23c) {
        this.gba23c = gba23c;
    }

    public String getGba24c() {
        return this.gba24c;
    }
    
    public void setGba24c(String gba24c) {
        this.gba24c = gba24c;
    }

    public String getGba25c() {
        return this.gba25c;
    }
    
    public void setGba25c(String gba25c) {
        this.gba25c = gba25c;
    }

    public String getGba26c() {
        return this.gba26c;
    }
    
    public void setGba26c(String gba26c) {
        this.gba26c = gba26c;
    }

    public String getGba27c() {
        return this.gba27c;
    }
    
    public void setGba27c(String gba27c) {
        this.gba27c = gba27c;
    }

    public Integer getGba28i() {
        return this.gba28i;
    }
    
    public void setGba28i(Integer gba28i) {
        this.gba28i = gba28i;
    }

    public String getGba29c() {
        return this.gba29c;
    }
    
    public void setGba29c(String gba29c) {
        this.gba29c = gba29c;
    }

    public String getGba30c() {
        return this.gba30c;
    }
    
    public void setGba30c(String gba30c) {
        this.gba30c = gba30c;
    }

    public String getGba31c() {
        return this.gba31c;
    }
    
    public void setGba31c(String gba31c) {
        this.gba31c = gba31c;
    }

    public String getGba32c() {
        return this.gba32c;
    }
    
    public void setGba32c(String gba32c) {
        this.gba32c = gba32c;
    }

    public String getGba33c() {
        return this.gba33c;
    }
    
    public void setGba33c(String gba33c) {
        this.gba33c = gba33c;
    }

    public String getGba34c() {
        return this.gba34c;
    }
    
    public void setGba34c(String gba34c) {
        this.gba34c = gba34c;
    }

    public String getGba35c() {
        return this.gba35c;
    }
    
    public void setGba35c(String gba35c) {
        this.gba35c = gba35c;
    }

    public String getGba36c() {
        return this.gba36c;
    }
    
    public void setGba36c(String gba36c) {
        this.gba36c = gba36c;
    }

    public String getGba37c() {
        return this.gba37c;
    }
    
    public void setGba37c(String gba37c) {
        this.gba37c = gba37c;
    }

    public String getGba38c() {
        return this.gba38c;
    }
    
    public void setGba38c(String gba38c) {
        this.gba38c = gba38c;
    }

    public Integer getGba39i() {
        return this.gba39i;
    }
    
    public void setGba39i(Integer gba39i) {
        this.gba39i = gba39i;
    }

    public String getGba40c() {
        return this.gba40c;
    }
    
    public void setGba40c(String gba40c) {
        this.gba40c = gba40c;
    }

	public String getGba41c() {
		return gba41c;
	}

	public void setGba41c(String gba41c) {
		this.gba41c = gba41c;
	}
}