package com.amani.old.model;



/**
 * Gcm01Id generated by MyEclipse - Hibernate Tools
 */

public class Gcm01Id  implements java.io.Serializable {


    // Fields    

     private String gca00c;
     private String gca01c;


    // Constructors

    /** default constructor */
    public Gcm01Id() {
    }

    
    /** full constructor */
    public Gcm01Id(String gca00c, String gca01c) {
        this.gca00c = gca00c;
        this.gca01c = gca01c;
    }

   
    // Property accessors

    public String getGca00c() {
        return this.gca00c;
    }
    
    public void setGca00c(String gca00c) {
        this.gca00c = gca00c;
    }

    public String getGca01c() {
        return this.gca01c;
    }
    
    public void setGca01c(String gca01c) {
        this.gca01c = gca01c;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Gcm01Id) ) return false;
		 Gcm01Id castOther = ( Gcm01Id ) other; 
         
		 return ( (this.getGca00c()==castOther.getGca00c()) || ( this.getGca00c()!=null && castOther.getGca00c()!=null && this.getGca00c().equals(castOther.getGca00c()) ) )
 && ( (this.getGca01c()==castOther.getGca01c()) || ( this.getGca01c()!=null && castOther.getGca01c()!=null && this.getGca01c().equals(castOther.getGca01c()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGca00c() == null ? 0 : this.getGca00c().hashCode() );
         result = 37 * result + ( getGca01c() == null ? 0 : this.getGca01c().hashCode() );
         return result;
   }   





}