package com.amani.old.model;
// default package



/**
 * Gcm01 generated by MyEclipse - Hibernate Tools
 */

public class Gcm01  implements java.io.Serializable {


    // Fields    

     //private String gca01c;
     //private String gca00c;
	 private Gcm01Id id;
     private String gca02c;
     private Integer gca03i;
     private String gca04c;
     private String gca05d;
     private String gca06d;
     private String gca07d;
     private Integer gca08i;
     private String gca09c;
     private Double gca10f;
     private String gca11c;
     private String gca12c;
     private String gca13d;
     private Integer gca14i;
     private Integer gca15i;
     private String gca16d;
     private String gca17d;
     private String gca18c;
     private Double gca19f;
     private String gca20c;
     private String gca21d;
     private String gca22d;
     private Integer gca23i;
     private Double gca24f;
     private Double gca25f;
     private Double gca26f;
     private String gca27c;
     private Integer gca28i;
     private String gca30c;
     private String gca31c;
     private Integer gca32i;
     private Integer gca33i;
     private Double gca34f;
     private String gca35c;

     /**标准金额 ****/
     private String gba03c;
     /**卡类别名称 ****/
     private String gak02c;
     /**标准金额 ****/
     private String gak09f;
     
     private String gak16f;
     
     private Integer gak14i;
     
     private String strCardType;
     private String strCardState;
     private Double	remainAmt;


    // Constructors

    public Gcm01(Gcm01Id id, String gca02c) {
		super();
		this.id = id;
		this.gca02c = gca02c;
	}

	public Gcm01(Gcm01Id id, String gca02c, Integer gca03i, String gca04c, String gca05d, String gca06d, String gca07d, Integer gca08i, String gca09c, Double gca10f, String gca11c, String gca12c, String gca13d, Integer gca14i, Integer gca15i, String gca16d, String gca17d, String gca18c, Double gca19f, String gca20c, String gca21d, String gca22d, Integer gca23i, Double gca24f, Double gca25f, Double gca26f, String gca27c, Integer gca28i, String gca30c, String gca31c, Integer gca32i, Integer gca33i, Double gca34f, String gca35c) {
		super();
		this.id = id;
		this.gca02c = gca02c;
		this.gca03i = gca03i;
		this.gca04c = gca04c;
		this.gca05d = gca05d;
		this.gca06d = gca06d;
		this.gca07d = gca07d;
		this.gca08i = gca08i;
		this.gca09c = gca09c;
		this.gca10f = gca10f;
		this.gca11c = gca11c;
		this.gca12c = gca12c;
		this.gca13d = gca13d;
		this.gca14i = gca14i;
		this.gca15i = gca15i;
		this.gca16d = gca16d;
		this.gca17d = gca17d;
		this.gca18c = gca18c;
		this.gca19f = gca19f;
		this.gca20c = gca20c;
		this.gca21d = gca21d;
		this.gca22d = gca22d;
		this.gca23i = gca23i;
		this.gca24f = gca24f;
		this.gca25f = gca25f;
		this.gca26f = gca26f;
		this.gca27c = gca27c;
		this.gca28i = gca28i;
		this.gca30c = gca30c;
		this.gca31c = gca31c;
		this.gca32i = gca32i;
		this.gca33i = gca33i;
		this.gca34f = gca34f;
		this.gca35c = gca35c;
		
	}

	public String getGak02c() {
		return gak02c;
	}

	public void setGak02c(String gak02c) {
		this.gak02c = gak02c;
	}

	public String getGak09f() {
		return gak09f;
	}

	public void setGak09f(String gak09f) {
		this.gak09f = gak09f;
	}

	public Integer getGak14i() {
		return gak14i;
	}

	public void setGak14i(Integer gak14i) {
		this.gak14i = gak14i;
	}

	public String getGak16f() {
		return gak16f;
	}

	public void setGak16f(String gak16f) {
		this.gak16f = gak16f;
	}

	public String getGba03c() {
		return gba03c;
	}

	public void setGba03c(String gba03c) {
		this.gba03c = gba03c;
	}

	public Double getRemainAmt() {
		return remainAmt;
	}

	public void setRemainAmt(Double remainAmt) {
		this.remainAmt = remainAmt;
	}

	public String getStrCardState() {
		return strCardState;
	}

	public void setStrCardState(String strCardState) {
		this.strCardState = strCardState;
	}

	public String getStrCardType() {
		return strCardType;
	}

	public void setStrCardType(String strCardType) {
		this.strCardType = strCardType;
	}

	/** default constructor */
    public Gcm01() {
    }

	/** minimal constructor */
    public Gcm01(String gca01c, String gca00c, String gca02c) {
        this.id.setGca00c(gca00c);
        this.id.setGca01c(gca01c);
        this.gca02c = gca02c;
    }
    
    /** full constructor */
    public Gcm01(String gca01c, String gca00c, String gca02c, Integer gca03i, String gca04c, String gca05d, String gca06d, String gca07d, Integer gca08i, String gca09c, Double gca10f, String gca11c, String gca12c, String gca13d, Integer gca14i, Integer gca15i, String gca16d, String gca17d, String gca18c, Double gca19f, String gca20c, String gca21d, String gca22d, Integer gca23i, Double gca24f, Double gca25f, Double gca26f, String gca27c, Integer gca28i, String gca30c, String gca31c, Integer gca32i, Integer gca33i, Double gca34f, String gca35c) {
        this.id.setGca00c(gca00c);
        this.id.setGca01c(gca01c);
        this.gca02c = gca02c;
        this.gca03i = gca03i;
        this.gca04c = gca04c;
        this.gca05d = gca05d;
        this.gca06d = gca06d;
        this.gca07d = gca07d;
        this.gca08i = gca08i;
        this.gca09c = gca09c;
        this.gca10f = gca10f;
        this.gca11c = gca11c;
        this.gca12c = gca12c;
        this.gca13d = gca13d;
        this.gca14i = gca14i;
        this.gca15i = gca15i;
        this.gca16d = gca16d;
        this.gca17d = gca17d;
        this.gca18c = gca18c;
        this.gca19f = gca19f;
        this.gca20c = gca20c;
        this.gca21d = gca21d;
        this.gca22d = gca22d;
        this.gca23i = gca23i;
        this.gca24f = gca24f;
        this.gca25f = gca25f;
        this.gca26f = gca26f;
        this.gca27c = gca27c;
        this.gca28i = gca28i;
        this.gca30c = gca30c;
        this.gca31c = gca31c;
        this.gca32i = gca32i;
        this.gca33i = gca33i;
        this.gca34f = gca34f;
        this.gca35c = gca35c;
    }

   
    // Property accessors


    public String getGca02c() {
        return this.gca02c;
    }
    
    public void setGca02c(String gca02c) {
        this.gca02c = gca02c;
    }

    public Integer getGca03i() {
        return this.gca03i;
    }
    
    public void setGca03i(Integer gca03i) {
        this.gca03i = gca03i;
    }

    public String getGca04c() {
        return this.gca04c;
    }
    
    public void setGca04c(String gca04c) {
        this.gca04c = gca04c;
    }

    public String getGca05d() {
        return this.gca05d;
    }
    
    public void setGca05d(String gca05d) {
        this.gca05d = gca05d;
    }

    public String getGca06d() {
        return this.gca06d;
    }
    
    public void setGca06d(String gca06d) {
        this.gca06d = gca06d;
    }

    public String getGca07d() {
        return this.gca07d;
    }
    
    public void setGca07d(String gca07d) {
        this.gca07d = gca07d;
    }

    public Integer getGca08i() {
        return this.gca08i;
    }
    
    public void setGca08i(Integer gca08i) {
        this.gca08i = gca08i;
    }

    public String getGca09c() {
        return this.gca09c;
    }
    
    public void setGca09c(String gca09c) {
        this.gca09c = gca09c;
    }

    public Double getGca10f() {
        return this.gca10f;
    }
    
    public void setGca10f(Double gca10f) {
        this.gca10f = gca10f;
    }

    public String getGca11c() {
        return this.gca11c;
    }
    
    public void setGca11c(String gca11c) {
        this.gca11c = gca11c;
    }

    public String getGca12c() {
        return this.gca12c;
    }
    
    public void setGca12c(String gca12c) {
        this.gca12c = gca12c;
    }

    public String getGca13d() {
        return this.gca13d;
    }
    
    public void setGca13d(String gca13d) {
        this.gca13d = gca13d;
    }

    public Integer getGca14i() {
        return this.gca14i;
    }
    
    public void setGca14i(Integer gca14i) {
        this.gca14i = gca14i;
    }

    public Integer getGca15i() {
        return this.gca15i;
    }
    
    public void setGca15i(Integer gca15i) {
        this.gca15i = gca15i;
    }

    public String getGca16d() {
        return this.gca16d;
    }
    
    public void setGca16d(String gca16d) {
        this.gca16d = gca16d;
    }

    public String getGca17d() {
        return this.gca17d;
    }
    
    public void setGca17d(String gca17d) {
        this.gca17d = gca17d;
    }

    public String getGca18c() {
        return this.gca18c;
    }
    
    public void setGca18c(String gca18c) {
        this.gca18c = gca18c;
    }

    public Double getGca19f() {
        return this.gca19f;
    }
    
    public void setGca19f(Double gca19f) {
        this.gca19f = gca19f;
    }

    public String getGca20c() {
        return this.gca20c;
    }
    
    public void setGca20c(String gca20c) {
        this.gca20c = gca20c;
    }

    public String getGca21d() {
        return this.gca21d;
    }
    
    public void setGca21d(String gca21d) {
        this.gca21d = gca21d;
    }

    public String getGca22d() {
        return this.gca22d;
    }
    
    public void setGca22d(String gca22d) {
        this.gca22d = gca22d;
    }

    public Integer getGca23i() {
        return this.gca23i;
    }
    
    public void setGca23i(Integer gca23i) {
        this.gca23i = gca23i;
    }

    public Double getGca24f() {
        return this.gca24f;
    }
    
    public void setGca24f(Double gca24f) {
        this.gca24f = gca24f;
    }

    public Double getGca25f() {
        return this.gca25f;
    }
    
    public void setGca25f(Double gca25f) {
        this.gca25f = gca25f;
    }

    public Double getGca26f() {
        return this.gca26f;
    }
    
    public void setGca26f(Double gca26f) {
        this.gca26f = gca26f;
    }

    public String getGca27c() {
        return this.gca27c;
    }
    
    public void setGca27c(String gca27c) {
        this.gca27c = gca27c;
    }

    public Integer getGca28i() {
        return this.gca28i;
    }
    
    public void setGca28i(Integer gca28i) {
        this.gca28i = gca28i;
    }

    public String getGca30c() {
        return this.gca30c;
    }
    
    public void setGca30c(String gca30c) {
        this.gca30c = gca30c;
    }

    public String getGca31c() {
        return this.gca31c;
    }
    
    public void setGca31c(String gca31c) {
        this.gca31c = gca31c;
    }

    public Integer getGca32i() {
        return this.gca32i;
    }
    
    public void setGca32i(Integer gca32i) {
        this.gca32i = gca32i;
    }

    public Integer getGca33i() {
        return this.gca33i;
    }
    
    public void setGca33i(Integer gca33i) {
        this.gca33i = gca33i;
    }

    public Double getGca34f() {
        return this.gca34f;
    }
    
    public void setGca34f(Double gca34f) {
        this.gca34f = gca34f;
    }

    public String getGca35c() {
        return this.gca35c;
    }
    
    public void setGca35c(String gca35c) {
        this.gca35c = gca35c;
    }

	public Gcm01Id getId() {
		return id;
	}

	public void setId(Gcm01Id id) {
		this.id = id;
	}
   








}