package com.amani.old.model;



/**
 * Gcm06 generated by MyEclipse - Hibernate Tools
 */

public class Gcm06  implements java.io.Serializable {


    // Fields    

     private Gcm06Id id;
     private String gcf01c;
     private String gcf02c;
     private Double gcf03f;
     private Double gcf04f;
     private Double gcf05f;
     private Double gcf06f;
     private Double gcf07f;
     private Double gcf08f;
     private Double gcf09f;
     private Double gcf10f;
     private String gcf11d;
     private String gcf12d;
     private Integer gcf13i;
     private Double gcf14f;
     private String gcf15c;
     private Integer gcf16i;
     private Integer gcf17i;
     private Double gcf18f;
     private Integer gcf19i;
     private Integer gcf20i;
     private Integer gcf21i;
     private Integer gcf22i;
     private Integer gcf24i;
     private Double gcf25f;
     private String projectName;
     private Double currentConsume;
     private Double dChangeAmt;
     private Double dChangeCount;
     private String gcf26c;
     private String gcf27c;
     /**疗程兑换使用***********************************/
     private String gcs08c;//第一销售
     private String gcs08cinid;//第一销售人员内部编号
     private Double gcs09f;//分享金额
 	 private String gcs10c;//第二销售
 	 private String gcs10cinid;//第二销售人员内部编号
 	 private Double gcs11f;//分享金额
 	 private String strFirstName;
 	 private String strSecondName;

    // Constructors

    public Double getDChangeAmt() {
		return dChangeAmt;
	}

	public void setDChangeAmt(Double changeAmt) {
		dChangeAmt = changeAmt;
	}

	public Double getCurrentConsume() {
		return currentConsume;
	}

	public void setCurrentConsume(Double currentConsume) {
		this.currentConsume = currentConsume;
	}

	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	/** default constructor */
    public Gcm06() {
    }

	/** minimal constructor */
    public Gcm06(Gcm06Id id, String gcf01c, String gcf02c, Integer gcf17i, Double gcf18f) {
        this.id = id;
        this.gcf01c = gcf01c;
        this.gcf02c = gcf02c;
        this.gcf17i = gcf17i;
        this.gcf18f = gcf18f;
    }
    
    /** full constructor */
    public Gcm06(Gcm06Id id, String gcf01c, String gcf02c, Double gcf03f, Double gcf04f, Double gcf05f, Double gcf06f, Double gcf07f, Double gcf08f, Double gcf09f, Double gcf10f, String gcf11d, String gcf12d, Integer gcf13i, Double gcf14f, String gcf15c, Integer gcf16i, Integer gcf17i, Double gcf18f, Integer gcf19i, Integer gcf20i, Integer gcf21i, Integer gcf22i, Integer gcf24i, Double gcf25f) {
        this.id = id;
        this.gcf01c = gcf01c;
        this.gcf02c = gcf02c;
        this.gcf03f = gcf03f;
        this.gcf04f = gcf04f;
        this.gcf05f = gcf05f;
        this.gcf06f = gcf06f;
        this.gcf07f = gcf07f;
        this.gcf08f = gcf08f;
        this.gcf09f = gcf09f;
        this.gcf10f = gcf10f;
        this.gcf11d = gcf11d;
        this.gcf12d = gcf12d;
        this.gcf13i = gcf13i;
        this.gcf14f = gcf14f;
        this.gcf15c = gcf15c;
        this.gcf16i = gcf16i;
        this.gcf17i = gcf17i;
        this.gcf18f = gcf18f;
        this.gcf19i = gcf19i;
        this.gcf20i = gcf20i;
        this.gcf21i = gcf21i;
        this.gcf22i = gcf22i;
        this.gcf24i = gcf24i;
        this.gcf25f = gcf25f;
    }

   
    // Property accessors

    public Gcm06Id getId() {
        return this.id;
    }
    
    public void setId(Gcm06Id id) {
        this.id = id;
    }

    public String getGcf01c() {
        return this.gcf01c;
    }
    
    public void setGcf01c(String gcf01c) {
        this.gcf01c = gcf01c;
    }

    public String getGcf02c() {
        return this.gcf02c;
    }
    
    public void setGcf02c(String gcf02c) {
        this.gcf02c = gcf02c;
    }

    public Double getGcf03f() {
        return this.gcf03f;
    }
    
    public void setGcf03f(Double gcf03f) {
        this.gcf03f = gcf03f;
    }

    public Double getGcf04f() {
        return this.gcf04f;
    }
    
    public void setGcf04f(Double gcf04f) {
        this.gcf04f = gcf04f;
    }

    public Double getGcf05f() {
        return this.gcf05f;
    }
    
    public void setGcf05f(Double gcf05f) {
        this.gcf05f = gcf05f;
    }

    public Double getGcf06f() {
        return this.gcf06f;
    }
    
    public void setGcf06f(Double gcf06f) {
        this.gcf06f = gcf06f;
    }

    public Double getGcf07f() {
        return this.gcf07f;
    }
    
    public void setGcf07f(Double gcf07f) {
        this.gcf07f = gcf07f;
    }

    public Double getGcf08f() {
        return this.gcf08f;
    }
    
    public void setGcf08f(Double gcf08f) {
        this.gcf08f = gcf08f;
    }

    public Double getGcf09f() {
        return this.gcf09f;
    }
    
    public void setGcf09f(Double gcf09f) {
        this.gcf09f = gcf09f;
    }

    public Double getGcf10f() {
        return this.gcf10f;
    }
    
    public void setGcf10f(Double gcf10f) {
        this.gcf10f = gcf10f;
    }

    public String getGcf11d() {
        return this.gcf11d;
    }
    
    public void setGcf11d(String gcf11d) {
        this.gcf11d = gcf11d;
    }

    public String getGcf12d() {
        return this.gcf12d;
    }
    
    public void setGcf12d(String gcf12d) {
        this.gcf12d = gcf12d;
    }

    public Integer getGcf13i() {
        return this.gcf13i;
    }
    
    public void setGcf13i(Integer gcf13i) {
        this.gcf13i = gcf13i;
    }

    public Double getGcf14f() {
        return this.gcf14f;
    }
    
    public void setGcf14f(Double gcf14f) {
        this.gcf14f = gcf14f;
    }

    public String getGcf15c() {
        return this.gcf15c;
    }
    
    public void setGcf15c(String gcf15c) {
        this.gcf15c = gcf15c;
    }

    public Integer getGcf16i() {
        return this.gcf16i;
    }
    
    public void setGcf16i(Integer gcf16i) {
        this.gcf16i = gcf16i;
    }

    public Integer getGcf17i() {
        return this.gcf17i;
    }
    
    public void setGcf17i(Integer gcf17i) {
        this.gcf17i = gcf17i;
    }

    public Double getGcf18f() {
        return this.gcf18f;
    }
    
    public void setGcf18f(Double gcf18f) {
        this.gcf18f = gcf18f;
    }

    public Integer getGcf19i() {
        return this.gcf19i;
    }
    
    public void setGcf19i(Integer gcf19i) {
        this.gcf19i = gcf19i;
    }

    public Integer getGcf20i() {
        return this.gcf20i;
    }
    
    public void setGcf20i(Integer gcf20i) {
        this.gcf20i = gcf20i;
    }

    public Integer getGcf21i() {
        return this.gcf21i;
    }
    
    public void setGcf21i(Integer gcf21i) {
        this.gcf21i = gcf21i;
    }

    public Integer getGcf22i() {
        return this.gcf22i;
    }
    
    public void setGcf22i(Integer gcf22i) {
        this.gcf22i = gcf22i;
    }

    public Integer getGcf24i() {
        return this.gcf24i;
    }
    
    public void setGcf24i(Integer gcf24i) {
        this.gcf24i = gcf24i;
    }

    public Double getGcf25f() {
        return this.gcf25f;
    }
    
    public void setGcf25f(Double gcf25f) {
        this.gcf25f = gcf25f;
    }

	public Double getDChangeCount() {
		return dChangeCount;
	}

	public void setDChangeCount(Double changeCount) {
		dChangeCount = changeCount;
	}

	public Double getdChangeAmt() {
		return dChangeAmt;
	}

	public void setdChangeAmt(Double dChangeAmt) {
		this.dChangeAmt = dChangeAmt;
	}

	public Double getdChangeCount() {
		return dChangeCount;
	}

	public void setdChangeCount(Double dChangeCount) {
		this.dChangeCount = dChangeCount;
	}

	public String getGcs08c() {
		return gcs08c;
	}

	public void setGcs08c(String gcs08c) {
		this.gcs08c = gcs08c;
	}

	public String getGcs08cinid() {
		return gcs08cinid;
	}

	public void setGcs08cinid(String gcs08cinid) {
		this.gcs08cinid = gcs08cinid;
	}

	public Double getGcs09f() {
		return gcs09f;
	}

	public void setGcs09f(Double gcs09f) {
		this.gcs09f = gcs09f;
	}

	public String getGcs10c() {
		return gcs10c;
	}

	public void setGcs10c(String gcs10c) {
		this.gcs10c = gcs10c;
	}

	public String getGcs10cinid() {
		return gcs10cinid;
	}

	public void setGcs10cinid(String gcs10cinid) {
		this.gcs10cinid = gcs10cinid;
	}

	public Double getGcs11f() {
		return gcs11f;
	}

	public void setGcs11f(Double gcs11f) {
		this.gcs11f = gcs11f;
	}

	public String getStrFirstName() {
		return strFirstName;
	}

	public void setStrFirstName(String strFirstName) {
		this.strFirstName = strFirstName;
	}

	public String getStrSecondName() {
		return strSecondName;
	}

	public void setStrSecondName(String strSecondName) {
		this.strSecondName = strSecondName;
	}

	public String getGcf26c() {
		return gcf26c;
	}

	public void setGcf26c(String gcf26c) {
		this.gcf26c = gcf26c;
	}

	public String getGcf27c() {
		return gcf27c;
	}

	public void setGcf27c(String gcf27c) {
		this.gcf27c = gcf27c;
	}
   
}