package com.amani.old.model;
// default package



/**
 * Gcm03Id generated by MyEclipse - Hibernate Tools
 */

public class Gcm03Id  implements java.io.Serializable {


    // Fields    
	 private String gcc00c;
     private String gcc01c;
     private Integer gcc03i;


    // Constructors

    /** default constructor */
    public Gcm03Id() {
    }

    
    /** full constructor */
    public Gcm03Id(String gcc01c, Integer gcc03i) {
        this.gcc01c = gcc01c;
        this.gcc03i = gcc03i;
    }

   
    // Property accessors

    public String getGcc01c() {
        return this.gcc01c;
    }
    
    public void setGcc01c(String gcc01c) {
        this.gcc01c = gcc01c;
    }

    public Integer getGcc03i() {
        return this.gcc03i;
    }
    
    public void setGcc03i(Integer gcc03i) {
        this.gcc03i = gcc03i;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Gcm03Id) ) return false;
		 Gcm03Id castOther = ( Gcm03Id ) other; 
         
		 return ( (this.getGcc01c()==castOther.getGcc01c()) || ( this.getGcc01c()!=null && castOther.getGcc01c()!=null && this.getGcc01c().equals(castOther.getGcc01c()) ) )
 && ( (this.getGcc03i()==castOther.getGcc03i()) || ( this.getGcc03i()!=null && castOther.getGcc03i()!=null && this.getGcc03i().equals(castOther.getGcc03i()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGcc01c() == null ? 0 : this.getGcc01c().hashCode() );
         result = 37 * result + ( getGcc03i() == null ? 0 : this.getGcc03i().hashCode() );
         return result;
   }


public String getGcc00c() {
	return gcc00c;
}


public void setGcc00c(String gcc00c) {
	this.gcc00c = gcc00c;
}   





}