package com.amani.old.model;



/**
 * Gcm02Id generated by MyEclipse - Hibernate Tools
 */

public class Gcm02Id  implements java.io.Serializable {


    // Fields    

     private String gcb00c;
     private String gcb01c;
     private Double gcb02f;


    // Constructors

    /** default constructor */
    public Gcm02Id() {
    }

    
    /** full constructor */
    public Gcm02Id(String gcb00c, String gcb01c, Double gcb02f) {
        this.gcb00c = gcb00c;
        this.gcb01c = gcb01c;
        this.gcb02f = gcb02f;
    }

   
    // Property accessors

    public String getGcb00c() {
        return this.gcb00c;
    }
    
    public void setGcb00c(String gcb00c) {
        this.gcb00c = gcb00c;
    }

    public String getGcb01c() {
        return this.gcb01c;
    }
    
    public void setGcb01c(String gcb01c) {
        this.gcb01c = gcb01c;
    }

    public Double getGcb02f() {
        return this.gcb02f;
    }
    
    public void setGcb02f(Double gcb02f) {
        this.gcb02f = gcb02f;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Gcm02Id) ) return false;
		 Gcm02Id castOther = ( Gcm02Id ) other; 
         
		 return ( (this.getGcb00c()==castOther.getGcb00c()) || ( this.getGcb00c()!=null && castOther.getGcb00c()!=null && this.getGcb00c().equals(castOther.getGcb00c()) ) )
 && ( (this.getGcb01c()==castOther.getGcb01c()) || ( this.getGcb01c()!=null && castOther.getGcb01c()!=null && this.getGcb01c().equals(castOther.getGcb01c()) ) )
 && ( (this.getGcb02f()==castOther.getGcb02f()) || ( this.getGcb02f()!=null && castOther.getGcb02f()!=null && this.getGcb02f().equals(castOther.getGcb02f()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGcb00c() == null ? 0 : this.getGcb00c().hashCode() );
         result = 37 * result + ( getGcb01c() == null ? 0 : this.getGcb01c().hashCode() );
         result = 37 * result + ( getGcb02f() == null ? 0 : this.getGcb02f().hashCode() );
         return result;
   }   





}