package com.amani.old.model;
// default package



/**
 * Gcm03 generated by MyEclipse - Hibernate Tools
 */

public class Gcm03  implements java.io.Serializable {


    // Fields    

     private Gcm03Id id;
     private Double gcc02f;
     private String gcc04c;
     private String gcc05c;
     private Double gcc06f;
     private Double gcc07f;
     private String gcc08c;
     private String gcc09d;
     private Double gcc10f;
     private String gcc11c;
     private String strAccountName;

    // Constructors

    public String getStrAccountName() {
		return strAccountName;
	}

	public void setStrAccountName(String strAccountName) {
		this.strAccountName = strAccountName;
	}

	/** default constructor */
    public Gcm03() {
    }

	/** minimal constructor */
    public Gcm03(Gcm03Id id, Double gcc02f) {
        this.id = id;
        this.gcc02f = gcc02f;
    }
    
    /** full constructor */
    public Gcm03(Gcm03Id id, Double gcc02f, String gcc04c, String gcc05c, Double gcc06f, Double gcc07f, String gcc08c, String gcc09d, Double gcc10f, String gcc11c) {
        this.id = id;
        this.gcc02f = gcc02f;
        this.gcc04c = gcc04c;
        this.gcc05c = gcc05c;
        this.gcc06f = gcc06f;
        this.gcc07f = gcc07f;
        this.gcc08c = gcc08c;
        this.gcc09d = gcc09d;
        this.gcc10f = gcc10f;
        this.gcc11c = gcc11c;
    }

   
    // Property accessors

    public Gcm03Id getId() {
        return this.id;
    }
    
    public void setId(Gcm03Id id) {
        this.id = id;
    }

    public Double getGcc02f() {
        return this.gcc02f;
    }
    
    public void setGcc02f(Double gcc02f) {
        this.gcc02f = gcc02f;
    }

    public String getGcc04c() {
        return this.gcc04c;
    }
    
    public void setGcc04c(String gcc04c) {
        this.gcc04c = gcc04c;
    }

    public String getGcc05c() {
        return this.gcc05c;
    }
    
    public void setGcc05c(String gcc05c) {
        this.gcc05c = gcc05c;
    }

    public Double getGcc06f() {
        return this.gcc06f;
    }
    
    public void setGcc06f(Double gcc06f) {
        this.gcc06f = gcc06f;
    }

    public Double getGcc07f() {
        return this.gcc07f;
    }
    
    public void setGcc07f(Double gcc07f) {
        this.gcc07f = gcc07f;
    }

    public String getGcc08c() {
        return this.gcc08c;
    }
    
    public void setGcc08c(String gcc08c) {
        this.gcc08c = gcc08c;
    }

    public String getGcc09d() {
        return this.gcc09d;
    }
    
    public void setGcc09d(String gcc09d) {
        this.gcc09d = gcc09d;
    }

    public Double getGcc10f() {
        return this.gcc10f;
    }
    
    public void setGcc10f(Double gcc10f) {
        this.gcc10f = gcc10f;
    }

    public String getGcc11c() {
        return this.gcc11c;
    }
    
    public void setGcc11c(String gcc11c) {
        this.gcc11c = gcc11c;
    }
   








}