package com.amani.old.model;



/**
 * Gcm04 generated by MyEclipse - Hibernate Tools
 */

public class Gcm04  implements java.io.Serializable {


    // Fields    

     private Gcm04Id id;
     private String gcd03c;
     private Integer gcd05i;
     private Double gcd06f;
     private String gcd07c;
     private String gcd08c;
     private String gcd09d;
     private Double gcd10f;
     private String gcd11c;
     private Integer gcd12i;
     //add by lyj 2008-07-15  billtype
     private String  strAccountName;
     private String  strBillType;
     private Double  remain;
    // Constructors

	public Double getRemain() {
		return remain;
	}

	public void setRemain(Double remain) {
		this.remain = remain;
	}

	public String getStrAccountName() {
		return strAccountName;
	}

	public void setStrAccountName(String strAccountName) {
		this.strAccountName = strAccountName;
	}

	public String getStrBillType() {
		return strBillType;
	}

	public void setStrBillType(String strBillType) {
		this.strBillType = strBillType;
	}

	/** default constructor */
    public Gcm04() {
    }

	/** minimal constructor */
    public Gcm04(Gcm04Id id) {
        this.id = id;
    }
    
    /** full constructor */
    public Gcm04(Gcm04Id id, String gcd03c, Integer gcd05i, Double gcd06f, String gcd07c, String gcd08c, String gcd09d, Double gcd10f, String gcd11c, Integer gcd12i) {
        this.id = id;
        this.gcd03c = gcd03c;
        this.gcd05i = gcd05i;
        this.gcd06f = gcd06f;
        this.gcd07c = gcd07c;
        this.gcd08c = gcd08c;
        this.gcd09d = gcd09d;
        this.gcd10f = gcd10f;
        this.gcd11c = gcd11c;
        this.gcd12i = gcd12i;
    }

   
    // Property accessors

    public Gcm04Id getId() {
        return this.id;
    }
    
    public void setId(Gcm04Id id) {
        this.id = id;
    }

    public String getGcd03c() {
        return this.gcd03c;
    }
    
    public void setGcd03c(String gcd03c) {
        this.gcd03c = gcd03c;
    }

    public Integer getGcd05i() {
        return this.gcd05i;
    }
    
    public void setGcd05i(Integer gcd05i) {
        this.gcd05i = gcd05i;
    }

    public Double getGcd06f() {
        return this.gcd06f;
    }
    
    public void setGcd06f(Double gcd06f) {
        this.gcd06f = gcd06f;
    }

    public String getGcd07c() {
        return this.gcd07c;
    }
    
    public void setGcd07c(String gcd07c) {
        this.gcd07c = gcd07c;
    }

    public String getGcd08c() {
        return this.gcd08c;
    }
    
    public void setGcd08c(String gcd08c) {
        this.gcd08c = gcd08c;
    }

    public String getGcd09d() {
        return this.gcd09d;
    }
    
    public void setGcd09d(String gcd09d) {
        this.gcd09d = gcd09d;
    }

    public Double getGcd10f() {
        return this.gcd10f;
    }
    
    public void setGcd10f(Double gcd10f) {
        this.gcd10f = gcd10f;
    }

    public String getGcd11c() {
        return this.gcd11c;
    }
    
    public void setGcd11c(String gcd11c) {
        this.gcd11c = gcd11c;
    }

    public Integer getGcd12i() {
        return this.gcd12i;
    }
    
    public void setGcd12i(Integer gcd12i) {
        this.gcd12i = gcd12i;
    }
   








}