package com.amani.old.model;



/**
 * Gcm04Id generated by MyEclipse - Hibernate Tools
 */

public class Gcm04Id  implements java.io.Serializable {


    // Fields    

     private String gcd00c;
     private String gcd01c;
     private Integer gcd02i;
     private Double gcd04f;


    // Constructors

    /** default constructor */
    public Gcm04Id() {
    }

    
    /** full constructor */
    public Gcm04Id(String gcd00c, String gcd01c, Integer gcd02i, Double gcd04f) {
        this.gcd00c = gcd00c;
        this.gcd01c = gcd01c;
        this.gcd02i = gcd02i;
        this.gcd04f = gcd04f;
    }

   
    // Property accessors

    public String getGcd00c() {
        return this.gcd00c;
    }
    
    public void setGcd00c(String gcd00c) {
        this.gcd00c = gcd00c;
    }

    public String getGcd01c() {
        return this.gcd01c;
    }
    
    public void setGcd01c(String gcd01c) {
        this.gcd01c = gcd01c;
    }

    public Integer getGcd02i() {
        return this.gcd02i;
    }
    
    public void setGcd02i(Integer gcd02i) {
        this.gcd02i = gcd02i;
    }

    public Double getGcd04f() {
        return this.gcd04f;
    }
    
    public void setGcd04f(Double gcd04f) {
        this.gcd04f = gcd04f;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Gcm04Id) ) return false;
		 Gcm04Id castOther = ( Gcm04Id ) other; 
         
		 return ( (this.getGcd00c()==castOther.getGcd00c()) || ( this.getGcd00c()!=null && castOther.getGcd00c()!=null && this.getGcd00c().equals(castOther.getGcd00c()) ) )
 && ( (this.getGcd01c()==castOther.getGcd01c()) || ( this.getGcd01c()!=null && castOther.getGcd01c()!=null && this.getGcd01c().equals(castOther.getGcd01c()) ) )
 && ( (this.getGcd02i()==castOther.getGcd02i()) || ( this.getGcd02i()!=null && castOther.getGcd02i()!=null && this.getGcd02i().equals(castOther.getGcd02i()) ) )
 && ( (this.getGcd04f()==castOther.getGcd04f()) || ( this.getGcd04f()!=null && castOther.getGcd04f()!=null && this.getGcd04f().equals(castOther.getGcd04f()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGcd00c() == null ? 0 : this.getGcd00c().hashCode() );
         result = 37 * result + ( getGcd01c() == null ? 0 : this.getGcd01c().hashCode() );
         result = 37 * result + ( getGcd02i() == null ? 0 : this.getGcd02i().hashCode() );
         result = 37 * result + ( getGcd04f() == null ? 0 : this.getGcd04f().hashCode() );
         return result;
   }   





}