package com.amani.old.model;



/**
 * Gcm02 generated by MyEclipse - Hibernate Tools
 */

public class Gcm02  implements java.io.Serializable {


    // Fields    

     private Gcm02Id id;
     private Integer gcb03i;
     private String gcb04c;
     private Integer gcb05i;
     private Integer gcb06i;
     private String gcb07d;
     private String gcb08c;
     private String strType;//异动性质--gcb03i
     private String strBeforeState;//异动前状态--gcb05i
     private String strAfterState;//异动后状态--gcb06i
    // Constructors

    public String getStrAfterState() {
		return strAfterState;
	}

	public void setStrAfterState(String strAfterState) {
		this.strAfterState = strAfterState;
	}

	public String getStrBeforeState() {
		return strBeforeState;
	}

	public void setStrBeforeState(String strBeforeState) {
		this.strBeforeState = strBeforeState;
	}

	public String getStrType() {
		return strType;
	}

	public void setStrType(String strType) {
		this.strType = strType;
	}

	/** default constructor */
    public Gcm02() {
    }

	/** minimal constructor */
    public Gcm02(Gcm02Id id) {
        this.id = id;
    }
    
    /** full constructor */
    public Gcm02(Gcm02Id id, Integer gcb03i, String gcb04c, Integer gcb05i, Integer gcb06i, String gcb07d, String gcb08c) {
        this.id = id;
        this.gcb03i = gcb03i;
        this.gcb04c = gcb04c;
        this.gcb05i = gcb05i;
        this.gcb06i = gcb06i;
        this.gcb07d = gcb07d;
        this.gcb08c = gcb08c;
    }

   
    // Property accessors

    public Gcm02Id getId() {
        return this.id;
    }
    
    public void setId(Gcm02Id id) {
        this.id = id;
    }

    public Integer getGcb03i() {
        return this.gcb03i;
    }
    
    public void setGcb03i(Integer gcb03i) {
        this.gcb03i = gcb03i;
    }

    public String getGcb04c() {
        return this.gcb04c;
    }
    
    public void setGcb04c(String gcb04c) {
        this.gcb04c = gcb04c;
    }

    public Integer getGcb05i() {
        return this.gcb05i;
    }
    
    public void setGcb05i(Integer gcb05i) {
        this.gcb05i = gcb05i;
    }

    public Integer getGcb06i() {
        return this.gcb06i;
    }
    
    public void setGcb06i(Integer gcb06i) {
        this.gcb06i = gcb06i;
    }

    public String getGcb07d() {
        return this.gcb07d;
    }
    
    public void setGcb07d(String gcb07d) {
        this.gcb07d = gcb07d;
    }

    public String getGcb08c() {
        return this.gcb08c;
    }
    
    public void setGcb08c(String gcb08c) {
        this.gcb08c = gcb08c;
    }
   








}