package com.amani.old.model;



/**
 * Gcm06Id generated by MyEclipse - Hibernate Tools
 */

public class Gcm06Id  implements java.io.Serializable {


    // Fields    

     private String gcf00c;
     private Integer gcf23i;


    // Constructors

    /** default constructor */
    public Gcm06Id() {
    }

    
    /** full constructor */
    public Gcm06Id(String gcf00c, Integer gcf23i) {
        this.gcf00c = gcf00c;
        this.gcf23i = gcf23i;
    }

   
    // Property accessors

    public String getGcf00c() {
        return this.gcf00c;
    }
    
    public void setGcf00c(String gcf00c) {
        this.gcf00c = gcf00c;
    }

    public Integer getGcf23i() {
        return this.gcf23i;
    }
    
    public void setGcf23i(Integer gcf23i) {
        this.gcf23i = gcf23i;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Gcm06Id) ) return false;
		 Gcm06Id castOther = ( Gcm06Id ) other; 
         
		 return ( (this.getGcf00c()==castOther.getGcf00c()) || ( this.getGcf00c()!=null && castOther.getGcf00c()!=null && this.getGcf00c().equals(castOther.getGcf00c()) ) )
 && ( (this.getGcf23i()==castOther.getGcf23i()) || ( this.getGcf23i()!=null && castOther.getGcf23i()!=null && this.getGcf23i().equals(castOther.getGcf23i()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGcf00c() == null ? 0 : this.getGcf00c().hashCode() );
         result = 37 * result + ( getGcf23i() == null ? 0 : this.getGcf23i().hashCode() );
         return result;
   }   





}