package com.amani.old.model;



/**
 * Gcm20 generated by MyEclipse - Hibernate Tools
 */

public class Gcm20  implements java.io.Serializable {


    // Fields    

     private Gcm20Id id;
     private String gct02c;
     private String gct03c;
     private String gct04d;
     private String gct05c;
     private String gct06c;
     private String gct07c;
     private String gct08c;
     private Double gct09f;
     private Double gct10f;
     private Double gct11f;
     private Double gct12f;
     private String gct13c;
     private String gct14c;
     private String gct15c;
     private String gct16c;
     private String gct17c;
     private String gct18c;
     
     private String util;


    // Constructors

    public String getUtil() {
		return util;
	}

	public void setUtil(String util) {
		this.util = util;
	}

	/** default constructor */
    public Gcm20() {
    }

	/** minimal constructor */
    public Gcm20(Gcm20Id id, String gct02c, String gct03c, String gct04d) {
        this.id = id;
        this.gct02c = gct02c;
        this.gct03c = gct03c;
        this.gct04d = gct04d;
    }
    
    /** full constructor */
    public Gcm20(Gcm20Id id, String gct02c, String gct03c, String gct04d, String gct05c, String gct06c, String gct07c, String gct08c, Double gct09f, Double gct10f, Double gct11f, Double gct12f, String gct13c, String gct14c, String gct15c, String gct16c, String gct17c, String gct18c) {
        this.id = id;
        this.gct02c = gct02c;
        this.gct03c = gct03c;
        this.gct04d = gct04d;
        this.gct05c = gct05c;
        this.gct06c = gct06c;
        this.gct07c = gct07c;
        this.gct08c = gct08c;
        this.gct09f = gct09f;
        this.gct10f = gct10f;
        this.gct11f = gct11f;
        this.gct12f = gct12f;
        this.gct13c = gct13c;
        this.gct14c = gct14c;
        this.gct15c = gct15c;
        this.gct16c = gct16c;
        this.gct17c = gct17c;
        this.gct18c = gct18c;
    }

   
    // Property accessors

    public Gcm20Id getId() {
        return this.id;
    }
    
    public void setId(Gcm20Id id) {
        this.id = id;
    }

    public String getGct02c() {
        return this.gct02c;
    }
    
    public void setGct02c(String gct02c) {
        this.gct02c = gct02c;
    }

    public String getGct03c() {
        return this.gct03c;
    }
    
    public void setGct03c(String gct03c) {
        this.gct03c = gct03c;
    }

    public String getGct04d() {
        return this.gct04d;
    }
    
    public void setGct04d(String gct04d) {
        this.gct04d = gct04d;
    }

    public String getGct05c() {
        return this.gct05c;
    }
    
    public void setGct05c(String gct05c) {
        this.gct05c = gct05c;
    }

    public String getGct06c() {
        return this.gct06c;
    }
    
    public void setGct06c(String gct06c) {
        this.gct06c = gct06c;
    }

    public String getGct07c() {
        return this.gct07c;
    }
    
    public void setGct07c(String gct07c) {
        this.gct07c = gct07c;
    }

    public String getGct08c() {
        return this.gct08c;
    }
    
    public void setGct08c(String gct08c) {
        this.gct08c = gct08c;
    }

    public Double getGct09f() {
        return this.gct09f;
    }
    
    public void setGct09f(Double gct09f) {
        this.gct09f = gct09f;
    }

    public Double getGct10f() {
        return this.gct10f;
    }
    
    public void setGct10f(Double gct10f) {
        this.gct10f = gct10f;
    }

    public Double getGct11f() {
        return this.gct11f;
    }
    
    public void setGct11f(Double gct11f) {
        this.gct11f = gct11f;
    }

    public Double getGct12f() {
        return this.gct12f;
    }
    
    public void setGct12f(Double gct12f) {
        this.gct12f = gct12f;
    }

    public String getGct13c() {
        return this.gct13c;
    }
    
    public void setGct13c(String gct13c) {
        this.gct13c = gct13c;
    }

    public String getGct14c() {
        return this.gct14c;
    }
    
    public void setGct14c(String gct14c) {
        this.gct14c = gct14c;
    }

    public String getGct15c() {
        return this.gct15c;
    }
    
    public void setGct15c(String gct15c) {
        this.gct15c = gct15c;
    }

    public String getGct16c() {
        return this.gct16c;
    }
    
    public void setGct16c(String gct16c) {
        this.gct16c = gct16c;
    }

    public String getGct17c() {
        return this.gct17c;
    }
    
    public void setGct17c(String gct17c) {
        this.gct17c = gct17c;
    }

    public String getGct18c() {
        return this.gct18c;
    }
    
    public void setGct18c(String gct18c) {
        this.gct18c = gct18c;
    }
   








}